// ACAScript.js, ACA On-Exchange Script Flow Data
// Gates 0–6 per u65-aca-spec.md Section 2.2

export const ACA_GATES = [
  {
    id: "aca-0",
    num: 0,
    key: "gate0Ok",
    label: "Opening & Identity Verification",
    compliance: false,
    script: [
      "Hi, this is [Agent Name] with New Gen Health Solutions. Am I speaking with [Client Name]?",
      "Great. I'm a licensed health insurance agent and Ill be helping you review your health coverage options. Before we get started, I need to let you know this call may be recorded for quality and compliance purposes. Is that okay?",
      "Perfect. Let me verify a few things. Can you confirm your full legal name and date of birth?",
      "And can you confirm your state and ZIP code?",
      "I also need to confirm whether youve had a recent qualifying life event that may make you eligible for coverage, such as losing other coverage, moving, getting married, or having a baby.",
    ],
    notes: [
      "If consent is declined: explain recording is required per NGHS compliance policy and offer a secure online enrollment link instead.",
      "On state capture: derive stateBased signal. If NJ or PA, flag state-based exchange (Get Covered NJ or PA Pennie).",
      "Branch: If OEP → set enrollmentPeriod to OEP, skip Gate 1. If SEP → proceed to Gate 1.",
    ],
    checklist: [
      "Identity verified (name + DOB confirmed)",
      "Call recording consent obtained",
    ],
    gate: "Identity verified, consent obtained, enrollment period determined",
  },
  {
    id: "aca-1",
    num: 1,
    key: "gate1Ok",
    label: "SEP Qualification",
    compliance: false,
    conditional: true,
    conditionNote: "Only render if enrollmentPeriod === SEP. Skip entirely during OEP.",
    script: [
      "You mentioned a qualifying life event. Can you tell me a little more about what happened?",
      "When exactly did that happen? I need to make sure we're still within the 60-day enrollment window.",
    ],
    sepTable: [
      { type: "Loss of Coverage (job loss, COBRA end, aging off parent)", docs: "Termination letter, COBRA notice, prior plan end date", window: "60 days from loss date" },
      { type: "Marriage", docs: "Marriage certificate", window: "60 days from marriage date" },
      { type: "Birth / Adoption", docs: "Birth certificate / adoption decree", window: "60 days from birth/adoption date" },
      { type: "Permanent Move (new zip/county)", docs: "Proof of new address (lease, utility bill)", window: "60 days from move date" },
      { type: "Loss of Medicaid/CHIP", docs: "Medicaid termination notice", window: "60 days from termination" },
      { type: "Income change (above Medicaid threshold)", docs: "Pay stubs, tax return, employment letter", window: "60 days from change" },
    ],
    notes: [
      "COMPLIANCE: If the SEP window has expired, do NOT proceed with marketplace enrollment. Inform client of the deadline and explore off-exchange alternatives (transition to U65 flow if appropriate).",
      "If sepExpiringSoon (< 7 days remain): display urgency, 'SEP window closes [date]. Prioritize enrollment completion today.'",
    ],
    signals: [
      "sepValid → true/false (derived from sepDate + 60 days)",
      "sepExpiringSoon → true if < 7 days remain in SEP window",
    ],
    checklist: [
      "SEP qualifying event confirmed",
      "SEP date within 60-day window verified",
      "SEP documentation identified / noted",
    ],
    gate: "SEP event verified, within 60-day window",
  },
  {
    id: "aca-2",
    num: 2,
    key: "gate2Ok",
    label: "Household & Income Assessment",
    compliance: false,
    script: [
      "Now I need to understand your household so we can figure out what kind of financial help you qualify for. How many people are in your tax household, that's you, your spouse if filing jointly, and any dependents you claim?",
      "And what's your estimated total household income for 2026? This includes wages, self-employment income, Social Security, investment income, basically your modified adjusted gross income.",
    ],
    subsidyNote: "2026 SUBSIDY CLIFF: Enhanced PTCs from ARP/IRA expired 12/31/2025. Clients above 400% FPL have NO subsidy. This is the #1 reason to have the U65 off-exchange flow ready as a pivot.",
    fplTable: [
      { range: "0–138% FPL", subsidy: "Medicaid eligible (expansion states)", csr: "N/A", action: "Refer to Medicaid. NJ/VA/PA expanded. GA did NOT expand." },
      { range: "139–150% FPL", subsidy: "Max APTC + CSR", csr: "94% AV Silver", action: "Strongly recommend Silver plan for CSR benefits" },
      { range: "151–200% FPL", subsidy: "High APTC + CSR", csr: "87% AV Silver", action: "Recommend Silver. CSR makes Silver better than Gold." },
      { range: "201–250% FPL", subsidy: "Moderate APTC + CSR", csr: "73% AV Silver", action: "Silver still advantaged via CSR. Compare to Bronze." },
      { range: "251–400% FPL", subsidy: "APTC available, no CSR", csr: "None", action: "Compare Bronze vs Silver vs Gold based on utilization." },
      { range: "> 400% FPL", subsidy: "NO APTC (2026 subsidy cliff)", csr: "None", action: "Full price. Consider off-exchange alternatives → U65 flow." },
    ],
    subsidyEligibleScript: "[If subsidyEligible] Great news, based on what you've told me, you should qualify for a monthly tax credit of approximately $[estimatedAPTC] to lower your premium. That's applied automatically when we enroll.",
    noSubsidyScript: "[If > 400% FPL] Based on your income, you won't qualify for a premium subsidy on the marketplace this year. The enhanced subsidies that were available the last few years expired at the end of 2025. We have two options: I can show you full-price marketplace plans, or I can walk you through some private off-exchange alternatives that might be more affordable. Which would you prefer?",
    notes: [
      "On income + household size entry: auto-calculate FPL%. Display derived values.",
      "If client chooses off-exchange → transition to U65 flow. Pass clientProfile data to U65Context.",
    ],
    signals: [
      "subsidyCliffRisk → true if income is 380–420% FPL (border zone)",
      "medicaidLikely → true if income < 138% FPL AND state is NJ, PA, or VA",
      "csrEligible → true if income 100–250% FPL",
    ],
    checklist: [
      "Household size documented",
      "Income documented / estimated",
      "FPL% calculated and subsidy eligibility determined",
    ],
    gate: "Household + income documented, subsidy eligibility determined",
  },
  {
    id: "aca-3",
    num: 3,
    key: "gate3Ok",
    label: "Needs Analysis & Plan Preferences",
    compliance: false,
    script: [
      "Let me ask a few questions so I can narrow down the best plans for you.",
      "Do you have any doctors or specialists you need to keep seeing? If so, who are they and where are they located?",
      "Are you currently taking any prescription medications?",
      "How would you describe your healthcare usage, are you pretty healthy and mostly need preventive care, or do you have ongoing conditions or expect any procedures this year?",
      "And what's your monthly budget for health insurance?",
    ],
    metalGuidance: [
      "Low utilization + budget-conscious + no CSR → Bronze",
      "Low utilization + CSR eligible → Silver (CSR makes it better than Bronze)",
      "Moderate utilization → Silver",
      "High utilization / chronic conditions → Gold",
      "Very low income + expansion state → check Medicaid first",
    ],
    notes: [
      "Store providers in existingProviders[] array for network lookup.",
      "Store prescriptions in rxList[] for formulary check.",
      "planMismatch signal → true if selected plan contradicts needs (e.g., Bronze with high utilization)",
    ],
    signals: [
      "planMismatch → true if selected plan contradicts needs",
    ],
    checklist: [
      "Provider preferences documented",
      "Prescription list documented",
      "Utilization level assessed",
      "Budget range noted",
    ],
    gate: "Needs documented, metal level direction determined",
  },
  {
    id: "aca-4",
    num: 4,
    key: "gate4Ok",
    label: "Plan Presentation & Selection",
    compliance: false,
    script: [
      "Based on everything you've told me, I've pulled up [2–3] plans that look like the best fit. Let me walk you through each one.",
      "Plan 1 is [Carrier] [Plan Name], a [Metal Level] plan. Your monthly premium after the tax credit would be approximately $[amount]. The deductible is $[amount], and your copay for a primary care visit is $[amount]. Specialist visits are $[amount].",
      "[If CSR eligible] Because of your income level, Silver plans come with extra cost-sharing reductions that lower your deductible and copays. That's why Silver is really the best value for you even if Bronze looks cheaper on premium alone.",
      "Let me check that your doctors are in-network on the plan you're leaning toward. [Verify provider directory]",
      "And let me check your prescriptions on the formulary. [Verify drug coverage]",
    ],
    notes: [
      "COMPLIANCE: Never guarantee specific premium amounts until the application is processed. Use 'approximately' or 'estimated' language.",
      "At this point the agent should be in the exchange platform (Get Covered NJ, PA Pennie, or Healthcare.gov) running the plan comparison.",
      "planMismatch check, if agent selects Bronze for CSR-eligible client, flag it.",
    ],
    checklist: [
      "Plan benefits reviewed with client",
      "Network adequacy checked for client providers",
      "Formulary checked for client prescriptions",
      "Premium amount disclosed (with subsidy if applicable)",
    ],
    gate: "Plan presented, network/formulary verified, plan selected",
  },
  {
    id: "aca-5",
    num: 5,
    key: "gate5Ok",
    label: "Enrollment & Submission",
    compliance: false,
    script: [
      "Great choice. Let's get you enrolled. I'm going to walk you through the application now. I'll need some additional information.",
      "Can you confirm your Social Security Number? [Or application ID if already started]",
      "Do you want to apply the full estimated tax credit of $[estimatedAPTC] per month to lower your premium, or would you prefer to take a smaller amount now and get the rest as a refund at tax time?",
      "I'm submitting your enrollment now. [Process application]",
      "Your enrollment is confirmed. Your confirmation number is [number]. Your coverage effective date is [date]. Your first premium payment of $[amount] is due by [date].",
    ],
    exchangeNote: "Enrollment platform by state: NJ → Get Covered NJ (getcovered.nj.gov) | PA → PA Pennie (pennie.com) | VA, GA → Healthcare.gov",
    notes: [
      "COMPLIANCE: SSN is collected within the exchange platform, NOT in EnrollGen or any NGHS system. Agent enters directly into the exchange enrollment portal.",
      "Advise: If income is variable (self-employed, gig), recommend taking less APTC upfront to avoid repayment at tax time.",
      "COMPLIANCE: Always provide the confirmation number and effective date verbally AND offer to send via email/text.",
    ],
    signals: [
      "enrollmentSubmitted → true",
    ],
    checklist: [
      "APTC election amount confirmed",
      "Enrollment submitted successfully",
      "Confirmation number recorded: ___________",
      "Effective date confirmed: ___________",
      "First premium amount and due date disclosed",
    ],
    gate: "Enrollment submitted, confirmation number recorded",
  },
  {
    id: "aca-6",
    num: 6,
    key: "gate6Ok",
    label: "Closing & Follow-Up",
    compliance: false,
    script: [
      "Let me recap what we set up today. You're enrolled in [Plan Name] with [Carrier]. Your monthly premium is $[amount] after the tax credit. Coverage starts [date]. You'll receive a welcome packet from [Carrier] with your ID card and instructions for setting up your online portal.",
      "A few important things: make sure you pay your first premium by [date] or your coverage won't activate. If you need to see a doctor before your ID card arrives, you can call [Carrier] member services for a temporary ID.",
      "I'm going to follow up with you in about two weeks to make sure everything is set up and you have your ID card. What's the best way to reach you?",
      "Is there anything else I can help you with today? [Pause] Great. Thank you for trusting New Gen Health Solutions with your health coverage. Have a great day!",
    ],
    checklist: [
      "Coverage recap provided to client",
      "First premium payment instructions given",
      "Follow-up scheduled: Date _________ Method _________",
      "Client confirmed understanding of next steps",
    ],
    gate: "Call closed, follow-up scheduled",
  },
];
