export const callOpening = [
  {
    intent_code: 'CALL_OPEN_001_RECORDING_ANNOUNCE',
    intent_name: 'Agent announces call is being recorded',
    category: 'CALL_OPENING',
    subcategory: null,
    description:
      'Agent must clearly inform the beneficiary that the call is being recorded before any substantive discussion begins.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 50.5',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 1,
    must_precede: ['CALL_OPEN_002_RECORDING_CONSENT'],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: true,
    sample_phrases: [
      'I do need to let you know that this call is being recorded for quality assurance and compliance purposes.',
      'Before we begin, I want to make you aware that this call will be recorded.',
      'Just so you know, we do record all of our calls for quality and training purposes.',
      'I am required to inform you that this conversation is being recorded today.',
      'For compliance purposes, I need to let you know upfront that we are recording this call.',
    ],
    anti_patterns: [
      'So let me go ahead and get some information from you.',
      'We take quality very seriously here at our agency.',
      'This call may be monitored.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_002_RECORDING_CONSENT',
    intent_name: 'Beneficiary provides verbal consent to recording',
    category: 'CALL_OPENING',
    subcategory: null,
    description:
      'Beneficiary must verbally consent to the call being recorded before the enrollment discussion can continue.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 50.5',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 2,
    must_precede: [],
    must_follow: ['CALL_OPEN_001_RECORDING_ANNOUNCE'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: true,
    sample_phrases: [
      'Is it okay with you if we continue with the call being recorded?',
      'Do I have your permission to continue recording this call?',
      'Are you comfortable with us recording this conversation today?',
      'May I have your verbal consent to proceed with the recording?',
    ],
    anti_patterns: [
      'Great, so let me pull up your information.',
      'Alright, moving on to the plans.',
      'Okay, I will take that as a yes.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_003_RECORDING_DECLINE',
    intent_name: 'Beneficiary declines recording, call must end',
    category: 'CALL_OPENING',
    subcategory: null,
    description:
      'If the beneficiary declines the recording, the agent must end the call and cannot proceed with an enrollment discussion.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 50.5',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 2,
    must_precede: [],
    must_follow: ['CALL_OPEN_001_RECORDING_ANNOUNCE'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: true,
    sample_phrases: [
      'I completely understand. Unfortunately, I am not able to continue the call without recording consent. We can schedule an in-person appointment instead if you would prefer.',
      'No problem at all. Since we are unable to proceed without the recording, I can set you up with a face-to-face appointment or mail you some information instead.',
      'I respect that. Because we are required to record enrollment calls, we will need to end the call here. I can send you plan information in the mail if you would like.',
      'That is perfectly fine. We do have other options, I can send materials by mail or arrange an in-person meeting where recording is not required.',
    ],
    anti_patterns: [
      'Okay, well let me just go over a few things real quick anyway.',
      'That is fine, I will just turn off the recorder and we can keep talking.',
      'No worries, we will just keep this off the record then.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_004_AGENT_IDENTIFY_NAME',
    intent_name: 'Agent states their full name',
    category: 'CALL_OPENING',
    subcategory: null,
    description:
      'Agent must clearly state their full name so the beneficiary knows who they are speaking with.',
    cms_reference: '42 CFR 422.2274(b)',
    mcmg_section: 'Ch. 2, Sec. 50.3',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 3,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'My name is Sarah Johnson and I will be helping you today.',
      'Hi there, this is Michael Rodriguez calling.',
      'Good morning, my name is David Chen. Thank you for taking my call.',
      'You are speaking with Lisa Patel today.',
    ],
    anti_patterns: [
      'Hey, this is Sarah from the Medicare department.',
      'Hi, I am calling about your Medicare benefits.',
      'This is your Medicare advisor.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_005_AGENT_IDENTIFY_AGENCY',
    intent_name: 'Agent identifies their agency',
    category: 'CALL_OPENING',
    subcategory: null,
    description:
      'Agent must identify the agency or organization they represent so the beneficiary knows who is contacting them.',
    cms_reference: '42 CFR 422.2274(b)',
    mcmg_section: 'Ch. 2, Sec. 50.3',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 4,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'I am calling from Senior Benefits Group.',
      'I work with National Medicare Advisors.',
      'I am a licensed agent with Premier Health Insurance Solutions.',
      'I am reaching out on behalf of Integrity Benefits Partners.',
    ],
    anti_patterns: [
      'I am calling from Medicare.',
      'I am with the government Medicare office.',
      'I work for your insurance company.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_006_AGENT_LICENSED',
    intent_name: 'Agent confirms they are licensed/certified',
    category: 'CALL_OPENING',
    subcategory: null,
    description:
      'Agent confirms that they are a licensed and certified insurance agent authorized to discuss Medicare plans.',
    cms_reference: '42 CFR 422.2274(b)',
    mcmg_section: 'Ch. 2, Sec. 50.3',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 5,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'I am a licensed and certified insurance agent in your state.',
      'I am licensed to sell Medicare Advantage plans in Florida.',
      'I hold an active health insurance license and am certified with CMS to discuss Medicare plans.',
      'Just so you know, I am fully licensed and AHIP certified to help you with Medicare.',
    ],
    anti_patterns: [
      'I have been doing this for years, so I know all the plans.',
      'I am a Medicare expert.',
      'I have helped hundreds of people just like you.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_007_CALL_PURPOSE',
    intent_name: 'Agent states purpose of call',
    category: 'CALL_OPENING',
    subcategory: null,
    description:
      'Agent must clearly state the purpose of the call so the beneficiary understands why they are being contacted.',
    cms_reference: '42 CFR 422.2274(b)',
    mcmg_section: 'Ch. 2, Sec. 50.3',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 6,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'The reason for my call today is to follow up on your request for information about Medicare Advantage plans in your area.',
      'You had reached out to us about reviewing your Medicare options, so I am calling to go over what is available.',
      'I am calling because you expressed interest in learning about Medicare Advantage plans for the upcoming year.',
      'The purpose of this call is to help you compare Medicare Advantage plans and see if there is a better fit for your needs.',
      'You requested a callback to discuss your Medicare coverage options, and that is why I am reaching out today.',
    ],
    anti_patterns: [
      'I am calling to get you signed up for a better plan.',
      'Let me tell you about this great new Medicare plan.',
      'I have some important changes to your Medicare I need to tell you about.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_008_TPMO_DISCLAIMER',
    intent_name: 'TPMO disclaimer delivered',
    category: 'CALL_OPENING',
    subcategory: 'TPMO',
    description:
      'Agent must deliver the full TPMO disclaimer, including that they represent a Third Party Marketing Organization, the number of organizations and plans represented, and references to Medicare.gov and SHIP.',
    cms_reference: '42 CFR 422.2274(g)',
    mcmg_section: 'Ch. 2, Sec. 50.6',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 7,
    must_precede: [
      'PLAN_001_PLAN_NAME_STATED',
      'PLAN_002_CARRIER_NAME_STATED',
      'PLAN_003_PLAN_TYPE_EXPLAINED',
      'PLAN_004_PREMIUM_STATED',
    ],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: true,
    sample_phrases: [
      'I want to let you know that I represent a Third Party Marketing Organization. We work with multiple carriers, currently we represent 12 organizations offering over 40 Medicare Advantage plans in your area. You can always get more information by calling 1-800-MEDICARE or visiting Medicare.gov, and you can also contact your local SHIP for free personalized help.',
      'I work with a third-party marketing organization. We represent several organizations and plans in your area. We do not offer every plan available. You can also visit Medicare.gov or contact your local SHIP for free unbiased counseling.',
      'Before we get started, I am required to let you know that I am a licensed agent working with a TPMO. We represent several insurance companies and their Medicare plans. For unbiased help you can reach out to SHIP or Medicare.gov.',
      'I need to share an important disclosure with you. I work with a Third Party Marketing Organization that represents 8 carriers and over 30 Medicare Advantage plans in your county. You always have the option to get free, unbiased assistance from your State Health Insurance Assistance Program, or SHIP, and you can visit Medicare.gov to compare plans on your own.',
      'As required by Medicare, I want to let you know I am affiliated with a TPMO. We work with multiple insurance organizations offering a variety of Medicare Advantage plans. You are never obligated to enroll through me, you can always call 1-800-MEDICARE, visit Medicare.gov, or contact your local SHIP office for free help.',
    ],
    anti_patterns: [
      'We offer all the Medicare plans available in your area.',
      'I work with the best Medicare plans out there.',
      'I am an independent agent so I can get you the best deal.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_009_TPMO_WITHIN_60SEC',
    intent_name: 'TPMO disclaimer within 60 seconds',
    category: 'CALL_OPENING',
    subcategory: 'TPMO',
    description:
      'The TPMO disclaimer must be delivered within the first 60 seconds of the call. This is a timing-based compliance requirement.',
    cms_reference: '42 CFR 422.2274(g)',
    mcmg_section: 'Ch. 2, Sec. 50.6',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 7,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'minor',
    auto_fail: false,
    sample_phrases: [
      'Let me get my required disclosures out of the way right at the top here, I represent a TPMO that works with multiple carriers...',
      'First things first, I need to share an important disclosure before we go any further...',
      'Right off the bat I want to make sure I give you my TPMO disclaimer as required...',
    ],
    anti_patterns: [
      'Oh, I almost forgot, I should mention that I work with a TPMO.',
      'Before we wrap up, let me give you the disclaimer.',
      'So now that we have gone over the plans, I do need to mention I am with a TPMO.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_010_TPMO_ORG_COUNT',
    intent_name: 'Disclaimer includes org count',
    category: 'CALL_OPENING',
    subcategory: 'TPMO',
    description:
      'The TPMO disclaimer must include the number of organizations (carriers) the agent represents.',
    cms_reference: '42 CFR 422.2274(g)',
    mcmg_section: 'Ch. 2, Sec. 50.6',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 7,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'minor',
    auto_fail: false,
    sample_phrases: [
      'We currently represent 12 different insurance organizations in your area.',
      'Our agency works with 8 carriers that offer Medicare Advantage plans.',
      'I have access to plans from 10 different insurance companies.',
      'We are contracted with 15 organizations that provide Medicare Advantage coverage.',
    ],
    anti_patterns: [
      'We work with many different insurance companies.',
      'We represent a wide variety of carriers.',
      'We have access to lots of plans from different companies.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_011_TPMO_PLAN_COUNT',
    intent_name: 'Disclaimer includes plan count',
    category: 'CALL_OPENING',
    subcategory: 'TPMO',
    description:
      'The TPMO disclaimer must include the number of plans the agent can offer in the beneficiary area.',
    cms_reference: '42 CFR 422.2274(g)',
    mcmg_section: 'Ch. 2, Sec. 50.6',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 7,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'minor',
    auto_fail: false,
    sample_phrases: [
      'In your zip code, we have access to over 40 Medicare Advantage plans.',
      'There are about 35 plans available through our agency in your county.',
      'We can offer you a choice of 28 Medicare Advantage plans in your area.',
      'Based on your location, I can show you roughly 50 different plan options.',
    ],
    anti_patterns: [
      'We have a ton of plans to choose from.',
      'There are so many plans available for you.',
      'We offer every plan you could possibly want.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_012_TPMO_SHIP_MENTION',
    intent_name: 'Disclaimer includes SHIP reference',
    category: 'CALL_OPENING',
    subcategory: 'TPMO',
    description:
      'The TPMO disclaimer must include a reference to the State Health Insurance Assistance Program (SHIP) as a free, unbiased resource.',
    cms_reference: '42 CFR 422.2274(g)',
    mcmg_section: 'Ch. 2, Sec. 50.6',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 7,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'minor',
    auto_fail: false,
    sample_phrases: [
      'You also have the option of contacting your local SHIP, the State Health Insurance Assistance Program, for free unbiased counseling.',
      'If you would like a second opinion, SHIP offers free Medicare counseling in your state.',
      'Your local SHIP office can also help you compare plans at no cost, they are completely independent.',
      'I also want you to know about SHIP. That stands for State Health Insurance Assistance Program, and they provide free help to Medicare beneficiaries.',
    ],
    anti_patterns: [
      'You can always call Medicare if you have questions.',
      'Feel free to do your own research online.',
      'There are other resources out there if you want to look around.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_013_TPMO_MEDICARE_GOV',
    intent_name: 'Disclaimer includes Medicare.gov reference',
    category: 'CALL_OPENING',
    subcategory: 'TPMO',
    description:
      'The TPMO disclaimer must include a reference to Medicare.gov as a resource for plan comparison.',
    cms_reference: '42 CFR 422.2274(g)',
    mcmg_section: 'Ch. 2, Sec. 50.6',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 7,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'minor',
    auto_fail: false,
    sample_phrases: [
      'You can also visit Medicare.gov to compare plans on your own at any time.',
      'Medicare.gov is another great resource where you can look up plans and compare benefits side by side.',
      'If you ever want to do your own research, Medicare.gov lets you search every plan available in your area.',
      'And of course, you can always go to Medicare.gov or call 1-800-MEDICARE for additional information.',
    ],
    anti_patterns: [
      'You can look things up online if you want.',
      'There are websites where you can find plan information.',
      'The government has resources available too.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_014_OUTBOUND_PTC_VALID',
    intent_name: 'Outbound: PTC on file and valid',
    category: 'CALL_OPENING',
    subcategory: 'OUTBOUND',
    description:
      'For outbound calls, the agent must confirm that a valid Permission to Contact (PTC) is on file before proceeding with the enrollment discussion.',
    cms_reference: '42 CFR 422.2274(a)',
    mcmg_section: 'Ch. 2, Sec. 50.1',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 0,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: true,
    sample_phrases: [
      'I see here that you gave us permission to contact you on March 15th when you filled out the form online.',
      'According to our records, you requested a callback about Medicare Advantage plans on the 10th, is that correct?',
      'You submitted a request for information through our website last Tuesday, and I am following up on that today.',
      'I am calling because you gave us your permission to reach out when you spoke with one of our team members last week.',
    ],
    anti_patterns: [
      'I just wanted to give you a quick call about Medicare.',
      'We are calling everyone in your area about some new plans.',
      'Your name came up on our list so I figured I would give you a ring.',
    ],
  },
  {
    intent_code: 'CALL_OPEN_015_INBOUND_GREETING',
    intent_name: 'Inbound: professional greeting',
    category: 'CALL_OPENING',
    subcategory: 'INBOUND',
    description:
      'For inbound calls, the agent provides a professional greeting that includes their name and the organization name.',
    cms_reference: null,
    mcmg_section: 'Ch. 2, Sec. 50.2',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'CALL_OPENING',
    sequence_position: 1,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'minor',
    auto_fail: false,
    sample_phrases: [
      'Thank you for calling Senior Benefits Group, this is Sarah. How can I help you today?',
      'Good afternoon, you have reached National Medicare Advisors. My name is David, how can I assist you?',
      'Hello, and thank you for calling. This is Lisa with Premier Health Insurance Solutions. What can I do for you?',
      'Welcome to Integrity Benefits Partners. My name is Michael and I would be happy to help you with your Medicare questions.',
    ],
    anti_patterns: [
      'Hello?',
      'Yeah, go ahead.',
      'Medicare, how can I help you?',
    ],
  },
];
