export const eligibilityVerification = [
  {
    intent_code: 'ELIG_001_PARTS_AB_CONFIRM',
    intent_name: 'Confirms Parts A and B enrollment',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: null,
    description:
      'Agent must confirm that the beneficiary is enrolled in both Medicare Part A and Part B, as this is a requirement for Medicare Advantage enrollment.',
    cms_reference: '42 CFR 422.50(a)',
    mcmg_section: 'Ch. 2, Sec. 40.1',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ELIGIBILITY_VERIFICATION',
    sequence_position: 11,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'Can you confirm that you are currently enrolled in both Medicare Part A and Part B?',
      'To make sure you are eligible, I need to verify that you have both Part A and Part B active. Do you have both?',
      'Are you enrolled in Original Medicare with both Part A, which is your hospital coverage, and Part B, which covers doctor visits?',
      'Before we look at plans, I need to confirm your Parts A and B are active. Can you verify that for me?',
      'Do you currently have both Medicare Part A and Part B? You would need both to enroll in a Medicare Advantage plan.',
    ],
    anti_patterns: [
      'You have Medicare, right? Great, let us look at plans.',
      'Since you are on Medicare, you qualify.',
      'I will just assume your Medicare is all set.',
    ],
  },
  {
    intent_code: 'ELIG_002_PART_B_PREMIUM',
    intent_name: 'Confirms Part B premium responsibility',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: null,
    description:
      'Agent informs the beneficiary that they must continue paying their Part B premium even when enrolled in a Medicare Advantage plan.',
    cms_reference: '42 CFR 422.100(f)',
    mcmg_section: 'Ch. 2, Sec. 40.1.2',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ELIGIBILITY_VERIFICATION',
    sequence_position: 12,
    must_precede: [],
    must_follow: ['ELIG_001_PARTS_AB_CONFIRM'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'I do want to make sure you understand that even with a Medicare Advantage plan, you will still need to continue paying your Part B premium. That does not go away.',
      'One important thing to know is that your Part B premium, which is currently $185 per month for most people, will still be deducted from your Social Security. That is separate from any plan premium.',
      'Keep in mind that Medicare Advantage does not replace your Part B premium. You will continue paying that regardless of which plan you choose.',
      'Just to be clear, your monthly Part B premium stays the same whether you are in Original Medicare or a Medicare Advantage plan.',
    ],
    anti_patterns: [
      'This plan replaces everything, so you will not have any other costs.',
      'You will not need to worry about any other premiums.',
      'Medicare Advantage covers all your Medicare costs.',
    ],
  },
  {
    intent_code: 'ELIG_003_SERVICE_AREA_CHECK',
    intent_name: 'Verifies beneficiary lives in plan service area',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: null,
    description:
      'Agent verifies that the beneficiary lives within the service area of the plans being discussed.',
    cms_reference: '42 CFR 422.50(a)(3)',
    mcmg_section: 'Ch. 2, Sec. 40.2',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ELIGIBILITY_VERIFICATION',
    sequence_position: 13,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'I need to verify your home address to make sure the plans I show you are actually available where you live. What is your residential address?',
      'Medicare Advantage plans are specific to where you live, so can you confirm your current home address for me?',
      'Let me make sure you are in the service area. What city and county do you live in?',
      'To pull up the right plans, I need to confirm where you reside. Are you still at the address we have on file?',
      'Plans vary by location, so I want to make sure we are looking at the right ones. What is your primary residence?',
    ],
    anti_patterns: [
      'These plans are available everywhere so do not worry about your address.',
      'It does not matter where you live, you can enroll in any plan.',
      'We will figure out the address stuff later.',
    ],
  },
  {
    intent_code: 'ELIG_004_ZIP_CODE_CONFIRM',
    intent_name: 'Confirms beneficiary zip code',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: null,
    description:
      'Agent confirms the beneficiary zip code for accurate plan lookup.',
    cms_reference: '42 CFR 422.50(a)(3)',
    mcmg_section: 'Ch. 2, Sec. 40.2',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ELIGIBILITY_VERIFICATION',
    sequence_position: 13,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'What is your zip code? I want to make sure I am pulling up the plans available in your exact area.',
      'Can you give me your five-digit zip code so I can look up what is available near you?',
      'And your zip code is 33157, is that correct?',
      'Let me confirm — you are in the 85281 zip code?',
    ],
    anti_patterns: [
      'What state are you in? That is all I need.',
      'I already know what plans are available so we can skip that.',
      'Just give me your general area and we will be fine.',
    ],
  },
  {
    intent_code: 'ELIG_005_COUNTY_CONFIRM',
    intent_name: 'Confirms beneficiary county',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: null,
    description:
      'Agent confirms the beneficiary county, as plan availability and benefits can differ by county within the same zip code.',
    cms_reference: '42 CFR 422.50(a)(3)',
    mcmg_section: 'Ch. 2, Sec. 40.2',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ELIGIBILITY_VERIFICATION',
    sequence_position: 13,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'That zip code actually crosses county lines, so I need to confirm — are you in Miami-Dade County or Broward County?',
      'And what county are you in? That matters because plans can vary from county to county.',
      'Can you confirm your county for me? I want to make sure I am looking at the right plan options.',
      'I show two counties for that zip code. Do you live in Maricopa or Pinal County?',
    ],
    anti_patterns: [
      'Do not worry about the county, the plans are basically the same.',
      'I will just pick one, it probably does not matter.',
      'County does not really affect anything.',
    ],
  },
  {
    intent_code: 'ELIG_006_ELECTION_PERIOD_VERIFY',
    intent_name: 'Identifies applicable election period',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: null,
    description:
      'Agent identifies which election period the beneficiary is eligible to enroll under (AEP, OEP, IEP, SEP, etc.).',
    cms_reference: '42 CFR 422.62',
    mcmg_section: 'Ch. 2, Sec. 30.1',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ELIGIBILITY_VERIFICATION',
    sequence_position: 14,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'Right now we are in the Annual Enrollment Period, which runs from October 15th through December 7th. That is the window you can make changes to your Medicare Advantage coverage.',
      'It sounds like you just turned 65, so you are in your Initial Enrollment Period. That gives you a seven-month window around your birthday to enroll.',
      'Since you recently moved to a new service area, you have a Special Enrollment Period that allows you to choose a new plan.',
      'We are currently in the Open Enrollment Period, which runs January 1st through March 31st. During this time you can switch from one Medicare Advantage plan to another.',
      'Based on what you have told me, you qualify for a Special Enrollment Period due to your loss of employer coverage.',
    ],
    anti_patterns: [
      'You can enroll any time, there are no restrictions.',
      'Do not worry about enrollment periods, we can always get you in.',
      'I can sign you up right now regardless of the time of year.',
    ],
  },
  {
    intent_code: 'ELIG_007_SEP_REASON_DOCUMENTED',
    intent_name: 'SEP qualifying reason documented',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: 'SEP',
    description:
      'If the beneficiary is enrolling during a Special Enrollment Period, the agent documents the qualifying reason.',
    cms_reference: '42 CFR 422.62(b)',
    mcmg_section: 'Ch. 2, Sec. 30.4',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ELIGIBILITY_VERIFICATION',
    sequence_position: 14,
    must_precede: [],
    must_follow: ['ELIG_006_ELECTION_PERIOD_VERIFY'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'You mentioned you recently moved from Ohio to Florida. That qualifies you for a Special Enrollment Period based on a permanent change of address. When was your move date?',
      'Since you are losing your employer coverage at the end of the month, that gives you a Special Enrollment Period. I just need to document the date your coverage ends.',
      'Your dual-eligible status qualifies you for a continuous SEP, which means you can make changes to your plan at any time.',
      'Because you were recently released from incarceration, you have a Special Enrollment Period. Let me document that qualifying event.',
    ],
    anti_patterns: [
      'Everyone qualifies for a special enrollment, do not worry about it.',
      'I will just mark down that you have a qualifying event.',
      'We will figure out the reason later, let us just get you enrolled.',
    ],
  },
  {
    intent_code: 'ELIG_008_EFFECTIVE_DATE_STATED',
    intent_name: 'States plan effective date',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: null,
    description:
      'Agent clearly states when the new plan coverage would become effective.',
    cms_reference: '42 CFR 422.68',
    mcmg_section: 'Ch. 2, Sec. 30.6',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ELIGIBILITY_VERIFICATION',
    sequence_position: 15,
    must_precede: [],
    must_follow: ['ELIG_006_ELECTION_PERIOD_VERIFY'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'If you enroll today during the Annual Enrollment Period, your new plan would take effect on January 1st.',
      'Because this is an IEP enrollment, your coverage would start on the first day of the month after your Part B effective date.',
      'With your SEP, the effective date would be the first of the month following your enrollment. So if we complete this today, you would be covered starting April 1st.',
      'I want to make sure you understand the timing — if we submit your application today, your new plan starts on May 1st.',
    ],
    anti_patterns: [
      'Your plan starts right away.',
      'You will be covered immediately after we finish.',
      'Do not worry about when it starts, just know you will be covered.',
    ],
  },
  {
    intent_code: 'ELIG_009_MEDICAID_STATUS_CHECK',
    intent_name: 'Asks about Medicaid or dual-eligible status',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: null,
    description:
      'Agent asks whether the beneficiary receives Medicaid or has dual-eligible status, which affects plan options and benefits.',
    cms_reference: '42 CFR 422.52',
    mcmg_section: 'Ch. 2, Sec. 40.3',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ELIGIBILITY_VERIFICATION',
    sequence_position: 16,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'Do you currently receive any Medicaid benefits or assistance from your state?',
      'I need to ask — are you enrolled in Medicaid in addition to Medicare? That would make you what is called dual-eligible.',
      'Are you receiving any help from your state with your healthcare costs, like Medicaid or a Medicare Savings Program?',
      'Do you have both Medicare and Medicaid? Some people have both, and it can open up additional plan options for you.',
    ],
    anti_patterns: [
      'You do not look like someone on Medicaid so we will skip that.',
      'Medicaid does not really matter for what we are doing.',
      'That is only for low-income people so we can move on.',
    ],
  },
  {
    intent_code: 'ELIG_010_ESRD_STATUS_CHECK',
    intent_name: 'Asks about ESRD status',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: null,
    description:
      'Agent asks whether the beneficiary has End-Stage Renal Disease, which affects eligibility for certain Medicare Advantage plans.',
    cms_reference: '42 CFR 422.50(a)(2)',
    mcmg_section: 'Ch. 2, Sec. 40.4',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ELIGIBILITY_VERIFICATION',
    sequence_position: 17,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'I do need to ask — have you been diagnosed with End-Stage Renal Disease, or ESRD? That would be permanent kidney failure requiring dialysis or a transplant.',
      'Are you currently receiving dialysis or have you had a kidney transplant? I need to check your ESRD status for eligibility.',
      'One more eligibility question — do you have End-Stage Renal Disease? Thanks to recent changes, most people with ESRD can now enroll in MA plans, but I need to document it.',
      'Have you been diagnosed with kidney failure that requires regular dialysis?',
    ],
    anti_patterns: [
      'You seem healthy so we do not need to worry about ESRD.',
      'That question only applies to really sick people.',
      'I will just mark no on the ESRD question.',
    ],
  },
  {
    intent_code: 'ELIG_011_NO_PII_FOR_OPTIONS',
    intent_name: 'No MBI/SSN required for presenting options',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: 'PII_PROTECTION',
    description:
      'Agent must not ask for the Medicare Beneficiary Identifier or Social Security Number just to present plan options. PII is only needed at enrollment.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 50.8',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: false,
    sample_phrases: [
      'I do not need your Medicare number or Social Security number right now. We are just going to look at plan options. I will only need that information if you decide to enroll.',
      'To look up plans, all I need is your zip code. I will not ask for any personal identification numbers unless you choose to move forward with enrollment.',
      'I want you to know that I am not going to ask for your Medicare ID or Social Security number just to show you plans. That is only needed if you decide to enroll.',
    ],
    anti_patterns: [
      'I am going to need your Medicare number before we can look at any plans.',
      'Can you read me your Social Security number so I can pull up your options?',
      'Let me get your MBI real quick so I can see what you are eligible for.',
    ],
  },
  {
    intent_code: 'ELIG_012_ZIP_ONLY_FOR_PLANS',
    intent_name: 'Only zip code needed for plan lookup',
    category: 'ELIGIBILITY_VERIFICATION',
    subcategory: 'PII_PROTECTION',
    description:
      'Agent communicates that only a zip code is needed to look up available plan options, reinforcing that PII is not required for browsing.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 50.8',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'All I need from you right now is your zip code to see what plans are available in your area.',
      'I can pull up all the plan options with just your zip code. No personal information needed at this stage.',
      'To get started, just give me your zip code and I will show you everything that is available near you.',
      'Your zip code is all I need to run the plan search. We keep it simple at this point.',
    ],
    anti_patterns: [
      'I need your full address and date of birth to look up plans.',
      'Give me your name and Medicare number so I can search for plans.',
      'I will need some personal details before I can show you anything.',
    ],
  },
];
