export const enrollmentClosing = [
  {
    intent_code: 'ENROLL_001_ENROLLMENT_VOLUNTARY',
    intent_name: 'Confirms enrollment is voluntary',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent explicitly confirms that the enrollment decision is voluntary and the beneficiary is not being pressured or obligated to enroll.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 120.1',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 80,
    must_precede: ['ENROLL_002_VERBAL_CONSENT'],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: true,
    sample_phrases: [
      'Before we proceed, I need to confirm that this enrollment is completely voluntary. No one is requiring you to enroll in this plan. Are you choosing to enroll on your own free will?',
      'I want to make absolutely sure — you understand that this enrollment is entirely voluntary, correct? You are under no obligation to sign up today.',
      'Just to be clear, nobody is pressuring you into this decision. This enrollment is 100 percent voluntary. Do you confirm that you are choosing to enroll of your own accord?',
      'I am required to ask — is your decision to enroll in this plan voluntary? You are not being forced or pressured by anyone to make this choice, correct?',
    ],
    anti_patterns: [
      'Great, let me just get you signed up real quick.',
      'You made the right choice, let me lock this in for you.',
      'Since you said you liked the plan, I will go ahead and enroll you.',
    ],
  },
  {
    intent_code: 'ENROLL_002_VERBAL_CONSENT',
    intent_name: 'Beneficiary provides verbal consent to enroll',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent obtains a clear, affirmative verbal consent from the beneficiary to proceed with the enrollment application submission.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 120.2',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 81,
    must_precede: [],
    must_follow: ['ENROLL_001_ENROLLMENT_VOLUNTARY'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: true,
    sample_phrases: [
      'Do I have your verbal authorization to submit this enrollment application on your behalf? Please say yes or no.',
      'I need your verbal consent to proceed. Do you authorize me to submit your enrollment into the Humana Gold Plus plan?',
      'Can you please confirm out loud that you give your consent for me to submit this enrollment form to the carrier?',
      'I need a clear yes or no — do you authorize the submission of this Medicare Advantage enrollment application?',
    ],
    anti_patterns: [
      'Alright, I will go ahead and submit this for you.',
      'I am going to take your silence as a yes.',
      'Since you agreed earlier, I am submitting it now.',
    ],
  },
  {
    intent_code: 'ENROLL_003_ENROLLMENT_CONFIRMED',
    intent_name: 'Confirms enrollment has been submitted',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent confirms to the beneficiary that the enrollment application has been successfully submitted to the carrier.',
    cms_reference: '42 CFR 422.60',
    mcmg_section: 'Ch. 3, Sec. 120.3',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 82,
    must_precede: [],
    must_follow: ['ENROLL_002_VERBAL_CONSENT'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'Your enrollment application has been submitted to Humana. You are all set on our end.',
      'I have successfully submitted your enrollment into the Aetna Medicare Eagle Plus plan. The application is now with the carrier for processing.',
      'Great news — your enrollment form has been submitted. The carrier will now process your application.',
      'Your application has been sent to UnitedHealthcare. Your enrollment is now being processed.',
    ],
    anti_patterns: [
      'You are enrolled, congratulations on your new plan!',
      'Done! Your new plan starts tomorrow.',
      'We got you all set up, everything is finalized.',
    ],
  },
  {
    intent_code: 'ENROLL_004_CONFIRMATION_NUMBER',
    intent_name: 'Provides confirmation number',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent provides the beneficiary with a confirmation number or reference number for their enrollment application.',
    cms_reference: '42 CFR 422.60',
    mcmg_section: 'Ch. 3, Sec. 120.4',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 83,
    must_precede: [],
    must_follow: ['ENROLL_003_ENROLLMENT_CONFIRMED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'Your confirmation number is HG-2026-847291. I recommend writing that down for your records.',
      'Let me give you your confirmation number — it is AET-55012-MA. Please keep that in a safe place in case you need to reference your application.',
      'I want to make sure you have your confirmation number. It is UHC-2026-331987. Do you have something to write that down with?',
      'Your enrollment reference number is WC-MA-098712. You will want to keep that handy in case you need to follow up on your application.',
    ],
    anti_patterns: [
      'You do not need a confirmation number, we have it on file.',
      'I will send you the number later, do not worry about it now.',
      'The confirmation number is not important, just wait for your card.',
    ],
  },
  {
    intent_code: 'ENROLL_005_EFFECTIVE_DATE_CONFIRMED',
    intent_name: 'Confirms effective date',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent clearly states the effective date of the new plan so the beneficiary knows when their coverage will begin.',
    cms_reference: '42 CFR 422.68',
    mcmg_section: 'Ch. 3, Sec. 120.5',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 84,
    must_precede: [],
    must_follow: ['ENROLL_003_ENROLLMENT_CONFIRMED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'Your new plan will go into effect on January 1st, 2027. That is when your coverage under this plan will begin.',
      'The effective date for your enrollment is April 1st, 2026. Your current plan will cover you until then, and the new plan takes over on that date.',
      'Just to confirm, your new coverage will start on July 1st. You will receive your new plan ID card before that date.',
      'Your plan effective date is February 1st, 2027. Make sure you continue using your current plan until that date.',
    ],
    anti_patterns: [
      'Your coverage starts right away.',
      'I am not sure when it starts exactly, but it should be soon.',
      'Do not worry about the date, just start using the new card when it arrives.',
    ],
  },
  {
    intent_code: 'ENROLL_006_NEXT_STEPS_EXPLAINED',
    intent_name: 'Explains next steps after enrollment',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent explains what the beneficiary should expect to happen after the enrollment is submitted, including what materials they will receive and any actions they may need to take.',
    cms_reference: '42 CFR 422.60',
    mcmg_section: 'Ch. 3, Sec. 120.6',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 85,
    must_precede: [],
    must_follow: ['ENROLL_003_ENROLLMENT_CONFIRMED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'Here is what to expect next. You will receive an acknowledgement letter from the carrier within a few weeks, followed by your new member ID card and welcome kit before your effective date.',
      'Let me walk you through the next steps. The carrier will review your application, and you should receive a welcome packet in the mail within 2 to 3 weeks. That will include your new ID card.',
      'After this call, here is what happens. The carrier processes your application, you will get a confirmation letter, and then your member materials and ID card will arrive before your plan starts.',
      'So the next steps are: the carrier will send you an enrollment acknowledgement, then your welcome kit with your plan ID card will arrive about 2 weeks before your effective date.',
    ],
    anti_patterns: [
      'You are all done, nothing else to worry about.',
      'We will handle everything from here, you do not need to do anything.',
      'If you do not hear from them, just assume everything went through.',
    ],
  },
  {
    intent_code: 'ENROLL_007_CANCELLATION_RIGHTS',
    intent_name: 'Explains right to cancel enrollment',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent informs the beneficiary of their right to cancel or disenroll from the plan and the timeframe in which they can do so.',
    cms_reference: '42 CFR 422.74',
    mcmg_section: 'Ch. 3, Sec. 120.7',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 86,
    must_precede: [],
    must_follow: ['ENROLL_003_ENROLLMENT_CONFIRMED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'I also want you to know that you have the right to cancel this enrollment. If you change your mind, you can contact the carrier or call 1-800-MEDICARE to cancel before the effective date.',
      'You have the right to disenroll at any time before your plan becomes effective. If you decide this is not the right plan for you, simply call the carrier or Medicare to cancel.',
      'Just so you know, this is not a permanent commitment right now. You can cancel your enrollment before the effective date by calling the plan or Medicare directly.',
    ],
    anti_patterns: [
      'Once you are enrolled, there is no going back.',
      'You cannot cancel after today, so make sure you are sure.',
      'It is really hard to cancel once the application is submitted.',
    ],
  },
  {
    intent_code: 'ENROLL_008_CMS_REVIEW_PERIOD',
    intent_name: 'Mentions CMS review period',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent mentions that the enrollment is subject to CMS review and that the carrier will confirm once the enrollment is approved.',
    cms_reference: '42 CFR 422.60',
    mcmg_section: 'Ch. 3, Sec. 120.8',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 87,
    must_precede: [],
    must_follow: ['ENROLL_003_ENROLLMENT_CONFIRMED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'minor',
    auto_fail: false,
    sample_phrases: [
      'Your enrollment application will go through a CMS review process. The carrier will confirm your enrollment once it has been approved by Medicare.',
      'Just so you know, Medicare reviews all enrollment applications. The carrier will send you a confirmation once CMS has approved your enrollment.',
      'Your application is subject to review and approval by CMS. You should receive confirmation from the plan within a couple of weeks.',
    ],
    anti_patterns: [
      'You are guaranteed to be approved.',
      'There is no review, you are already in the plan.',
      'CMS always approves these, it is just a rubber stamp.',
    ],
  },
  {
    intent_code: 'ENROLL_009_CONTACT_INFO_PROVIDED',
    intent_name: 'Provides agent/agency contact info',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent provides the beneficiary with contact information for the agent or agency in case they have follow-up questions.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 120.9',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 88,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'If you have any questions after today, you can reach me directly at 555-123-4567. My name again is Sarah Johnson and I am happy to help anytime.',
      'Let me give you my contact information. You can call me at 555-987-6543 or email me at david.chen@seniorbenefits.com. I am available Monday through Friday.',
      'Here is how to reach us if you need anything. Our office number is 555-222-3344 and you can ask for me, Lisa Patel. We are here to help even after enrollment.',
      'I want to make sure you have a way to reach me. My direct number is 555-456-7890. Please do not hesitate to call if any questions come up.',
    ],
    anti_patterns: [
      'Just call Medicare if you have questions.',
      'You probably will not need to reach me again.',
      'I am not allowed to give out my direct number.',
    ],
  },
  {
    intent_code: 'ENROLL_010_CARRIER_CONTACT_PROVIDED',
    intent_name: 'Provides carrier member services contact',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent provides the beneficiary with the carrier member services phone number so they can contact the plan directly with questions or issues.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 120.10',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 89,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'I also want to give you the carrier member services number. For Humana, you can call 1-800-457-4708. They can help you with any plan-specific questions once your enrollment is processed.',
      'Once you are a member, you can reach Aetna member services at the number on your ID card. In the meantime, their general line is 1-800-545-5862.',
      'If you need to contact UnitedHealthcare directly, their member services number is 1-877-596-3258. That number will also be on your new member ID card.',
      'The carrier member services number for Wellcare is 1-866-530-9491. You can call them for questions about claims, benefits, or your ID card.',
    ],
    anti_patterns: [
      'Just call me for everything, do not bother the carrier.',
      'I do not have the carrier number handy.',
      'You will figure out their number when you get your card.',
    ],
  },
  {
    intent_code: 'ENROLL_011_NO_PRESSURE_TACTICS',
    intent_name: 'No pressure tactics used during enrollment',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent does not use any pressure tactics, urgency language, or coercive techniques to push the beneficiary toward enrollment.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 60.3',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: true,
    sample_phrases: [
      'Take all the time you need to think about this. There is no rush to make a decision today.',
      'I want you to feel completely comfortable with your choice. If you need more time, that is perfectly fine.',
      'This is a big decision and I want you to be sure. Would you like some time to talk it over with your family before proceeding?',
      'There is no deadline pressure here. You have until the end of the enrollment period to make your decision.',
    ],
    anti_patterns: [
      'This offer expires at midnight tonight so we need to act now.',
      'I only have a few spots left for this plan, so we should lock it in.',
      'If you wait, you might miss out and be stuck with your current plan.',
    ],
  },
  {
    intent_code: 'ENROLL_012_NO_INCENTIVES_OFFERED',
    intent_name: 'No incentives offered for enrollment',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent does not offer any gifts, incentives, cash, or other inducements to encourage the beneficiary to enroll in the plan.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 60.4',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: true,
    sample_phrases: [
      'The benefits I have described are the standard plan benefits available to all enrollees. I want to make sure you are choosing based on the coverage itself.',
      'Everything I have shared with you today is part of the plan standard benefits that every member receives.',
      'Your decision should be based solely on whether the plan benefits meet your healthcare needs.',
      'I am not able to offer anything beyond the standard plan benefits. The plan itself is what I want you to evaluate.',
    ],
    anti_patterns: [
      'If you sign up today, I can get you a free gift card.',
      'We have a special bonus for people who enroll on this call.',
      'I will throw in a free meal voucher if you enroll right now.',
    ],
  },
  {
    intent_code: 'ENROLL_013_BENEFICIARY_QUESTIONS',
    intent_name: 'Asks if beneficiary has questions',
    category: 'ENROLLMENT_CLOSING',
    subcategory: null,
    description:
      'Agent asks the beneficiary if they have any remaining questions before ending the call, ensuring the beneficiary has an opportunity to seek clarification.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 120.13',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'ENROLLMENT_CLOSING',
    sequence_position: 90,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'Before we wrap up, do you have any questions at all about the plan, the enrollment process, or anything else we discussed today?',
      'Is there anything else I can help you with or any questions you have before we end the call?',
      'I want to make sure I have addressed everything. Do you have any remaining questions or concerns?',
      'We have covered a lot of information today. Is there anything you would like me to go over again or any final questions?',
    ],
    anti_patterns: [
      'Alright, we are all done here. Goodbye.',
      'I think we covered everything so I will let you go.',
      'No questions? Great, talk to you later.',
    ],
  },
];
