export const preEnrollmentChecklist = [
  {
    intent_code: 'PECL_001_CHECKLIST_REFERENCED',
    intent_name: 'References the Pre-Enrollment Checklist',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent references the Pre-Enrollment Checklist (PECL) and begins walking through the required items with the beneficiary.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.1',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 65,
    must_precede: ['PECL_002_PREMIUM_CONFIRMED'],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'Now I need to go through the Pre-Enrollment Checklist with you. This is required by Medicare to make sure you understand the plan before enrolling.',
      'Before we can move forward with enrollment, I am required to review the Pre-Enrollment Checklist. This covers the key things you need to know about the plan.',
      'At this point, I need to walk through what is called the PECL, or Pre-Enrollment Checklist. It is a set of items Medicare requires me to review with you.',
      'Let me now go over the Pre-Enrollment Checklist. This is a CMS requirement to ensure you have all the important information before making your decision.',
    ],
    anti_patterns: [
      'Let me just quickly read through some stuff real fast.',
      'I have to read you some legal stuff, just say yes to everything.',
      'We can skip the checklist since you already know what you want.',
    ],
  },
  {
    intent_code: 'PECL_002_PREMIUM_CONFIRMED',
    intent_name: 'PECL: premium amount confirmed',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent confirms the plan monthly premium and the beneficiary acknowledges understanding the premium obligation.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.2',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 66,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'The monthly premium for this plan is $27 per month, and that is in addition to your Part B premium. Do you understand and agree to that amount?',
      'I want to confirm that the plan premium is zero dollars per month. You will still need to pay your Part B premium, but there is no additional plan premium. Does that make sense?',
      'Your plan premium will be $45 each month on top of your Medicare Part B premium. Can you confirm you understand that?',
      'So to be clear, this plan has a $0 premium. The only premium you pay is your regular Part B premium to Medicare. Do you acknowledge that?',
    ],
    anti_patterns: [
      'This plan is basically free.',
      'You do not have to pay anything with this plan.',
      'The premium is nothing to worry about.',
    ],
  },
  {
    intent_code: 'PECL_003_DEDUCTIBLE_CONFIRMED',
    intent_name: 'PECL: deductible amount confirmed',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent confirms the plan deductible amounts, including medical and drug deductibles, and the beneficiary acknowledges understanding.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.3',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 67,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'The medical deductible on this plan is $0, and the drug deductible is $150 for Tier 3 through 5 medications. Do you understand those deductible amounts?',
      'I want to confirm the deductibles with you. There is no medical deductible, and the Part D drug deductible is $545. Does that make sense?',
      'This plan has a $250 combined medical deductible and a $0 drug deductible. Can you confirm you understand how the deductibles work?',
    ],
    anti_patterns: [
      'There are no costs to worry about upfront.',
      'You probably will not hit your deductible anyway.',
      'The deductible is basically nothing.',
    ],
  },
  {
    intent_code: 'PECL_004_MOOP_CONFIRMED',
    intent_name: 'PECL: maximum out-of-pocket confirmed',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent confirms the plan maximum out-of-pocket (MOOP) limit and the beneficiary acknowledges understanding this is the most they would pay in a year.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.4',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 68,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'The maximum out-of-pocket for this plan is $3,900 for in-network services. That is the most you would pay in a year for covered medical services. Do you understand that?',
      'Your annual MOOP, or maximum out-of-pocket, is $5,900 in-network and $8,300 combined in and out of network. Once you hit that limit, the plan pays 100 percent. Does that make sense?',
      'I want to confirm the MOOP with you. The most you could pay out of pocket in a year is $4,500 for in-network care. Can you confirm you understand that limit?',
    ],
    anti_patterns: [
      'You will never actually pay that much.',
      'The out-of-pocket maximum is just a technicality.',
      'Do not worry about the MOOP, nobody ever reaches it.',
    ],
  },
  {
    intent_code: 'PECL_005_PROVIDER_NETWORK_CONFIRMED',
    intent_name: 'PECL: provider network confirmed',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent confirms that the beneficiary understands they must generally use in-network providers and has verified their doctors are in the plan network.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.5',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 69,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'Do you understand that with this HMO plan you will need to use in-network providers for your care to be covered? We already verified your doctors are in-network. Can you confirm you understand the network requirements?',
      'I want to confirm that you understand the provider network. You will need to see doctors and go to facilities that are part of the plan network. Have we checked that your current providers are in-network?',
      'As part of the checklist, I need to confirm you understand the network. With this PPO, you can go out of network but you will pay more. Have you confirmed your preferred doctors accept this plan?',
      'Can you confirm that you understand you need to use network providers and that we have verified your primary care doctor and specialists are in this plan network?',
    ],
    anti_patterns: [
      'All doctors accept Medicare Advantage plans.',
      'Your doctors are probably in-network, I would not worry about it.',
      'You can see whoever you want, there are no restrictions.',
    ],
  },
  {
    intent_code: 'PECL_006_PHARMACY_NETWORK_CONFIRMED',
    intent_name: 'PECL: pharmacy network confirmed',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent confirms that the beneficiary understands they should use in-network pharmacies and has verified their preferred pharmacy participates in the plan.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.6',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 70,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'For your prescriptions, you will want to use a pharmacy that is in the plan network. We checked and your CVS on Main Street is in-network. Do you understand the pharmacy network requirement?',
      'I also need to confirm you understand the pharmacy network. Using a preferred pharmacy will give you the lowest copays. Is the pharmacy you use regularly in this plan network?',
      'Have we confirmed that your preferred pharmacy participates in this plan network? You will want to fill your prescriptions at an in-network pharmacy to get the best pricing.',
    ],
    anti_patterns: [
      'You can use any pharmacy you want.',
      'All the major pharmacies are in every network.',
      'Do not worry about where you fill your prescriptions.',
    ],
  },
  {
    intent_code: 'PECL_007_DRUG_COVERAGE_CONFIRMED',
    intent_name: 'PECL: drug coverage confirmed',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent confirms that the beneficiary understands how their prescription drugs are covered under the plan formulary and any applicable tier copays or restrictions.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.7',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 71,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'We checked your medications against the plan formulary. Your Lisinopril is covered at a $3 copay and your Metformin is covered at $0. Do you confirm you understand how your drugs are covered?',
      'I want to confirm you understand the drug coverage. All of your current medications are on the plan formulary. Your estimated total monthly drug cost would be about $25. Does that make sense?',
      'As part of the checklist, I need to confirm you understand your prescription coverage. We ran your drugs through the formulary and they are all covered, though one of them does require a prior authorization. Do you understand that?',
      'Can you confirm that you understand how your prescriptions will be covered under this plan? We reviewed your drug list and everything is on the formulary at the tier levels I explained earlier.',
    ],
    anti_patterns: [
      'All your drugs are covered, do not worry about the details.',
      'The formulary changes every year so there is no point checking now.',
      'We did not check your drugs but they are probably covered.',
    ],
  },
  {
    intent_code: 'PECL_008_BENEFITS_UNDERSTOOD',
    intent_name: 'PECL: beneficiary confirms understanding of benefits',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent confirms that the beneficiary understands the overall benefits of the plan as presented, including what is covered and how the plan works.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.8',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 72,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'We have now gone through all the main benefits of this plan. Do you feel you have a good understanding of what is covered and how the plan works?',
      'I want to make sure you are comfortable with everything we have discussed about the plan benefits. Do you understand how the coverage works overall?',
      'Before we move to enrollment, can you confirm that you understand the plan benefits we have reviewed, including the medical, drug, and supplemental benefits?',
      'Do you have a clear understanding of the plan benefits we went over, the doctor visits, hospital coverage, prescription drugs, and the extra benefits like dental and vision?',
    ],
    anti_patterns: [
      'I am sure you got it, let us move on.',
      'This is all standard stuff, everybody gets the same thing.',
      'We covered a lot but the important thing is the price is right.',
    ],
  },
  {
    intent_code: 'PECL_009_COST_SHARING_UNDERSTOOD',
    intent_name: 'PECL: cost sharing understood',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent confirms that the beneficiary understands their cost-sharing obligations including copays, coinsurance, and how costs may vary by service type and provider network status.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.9',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 73,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'I want to make sure you understand your cost sharing. You will have copays for doctor visits, coinsurance for certain services, and those costs can be different depending on whether you use in-network or out-of-network providers. Do you understand that?',
      'Can you confirm you understand the cost-sharing structure? For example, your PCP visits are a $0 copay, specialist visits are $40, and hospital stays have a $250 per day copay for the first 5 days. Does that make sense?',
      'Do you understand that you will have out-of-pocket costs like copays and coinsurance when you use services, and those costs vary by the type of service? We went over the specifics earlier.',
      'As part of the checklist, I need you to confirm you understand your cost-sharing responsibilities, the copays, coinsurance amounts, and how they differ for in-network versus out-of-network care.',
    ],
    anti_patterns: [
      'Everything is basically covered so you do not need to worry about costs.',
      'The copays are so low they are practically free.',
      'You will never have to pay much out of pocket with this plan.',
    ],
  },
  {
    intent_code: 'PECL_010_DISENROLLMENT_UNDERSTOOD',
    intent_name: 'PECL: disenrollment effect understood',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent confirms that the beneficiary understands the effect of enrolling in this plan on their current coverage, including disenrollment from their existing plan.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.10',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 74,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: true,
    sample_phrases: [
      'I need to confirm that you understand, by enrolling in this plan, you will be automatically disenrolled from your current plan. Do you understand and acknowledge that?',
      'Can you confirm you understand that enrolling in this plan means your current coverage will end? You will be disenrolled from your existing plan on the day this new plan takes effect.',
      'As required by the checklist, do you acknowledge that you understand enrolling here means leaving your current plan? This change cannot be undone outside of an enrollment period.',
      'Do you understand that by proceeding with this enrollment, your current plan will be terminated and replaced by this plan? Can you confirm that?',
    ],
    anti_patterns: [
      'You can keep both plans, no worries.',
      'You can always just switch back if you change your mind.',
      'The disenrollment part is just a formality.',
    ],
  },
  {
    intent_code: 'PECL_011_PLAN_RULES_ACKNOWLEDGED',
    intent_name: 'PECL: plan rules acknowledged',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent confirms that the beneficiary understands the plan rules, including referral requirements, prior authorizations, and any restrictions on services.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.11',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 75,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'Do you understand the plan rules we discussed, including that you will need referrals to see specialists and that some services require prior authorization?',
      'I need you to confirm that you acknowledge the plan rules. With this HMO, you will need to choose a primary care doctor and get referrals for specialty care. Do you understand that?',
      'As part of the checklist, can you confirm you understand the plan rules, including any prior authorization requirements for certain procedures and medications?',
    ],
    anti_patterns: [
      'There really are not any rules to worry about.',
      'You can basically do whatever you want with this plan.',
      'The rules are just a formality, nobody enforces them.',
    ],
  },
  {
    intent_code: 'PECL_012_SUMMARY_OF_BENEFITS',
    intent_name: 'Summary of Benefits reviewed',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent references the Summary of Benefits document and confirms the beneficiary has received or will receive it for their review.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.12',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 76,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'I have also sent you the Summary of Benefits document for this plan. It has all the details we went over in writing. Did you receive that, or would you like me to send it to you?',
      'You will be receiving a Summary of Benefits document that outlines everything we discussed today. I want to make sure you have that for your records.',
      'The Summary of Benefits is a document that lists all the plan costs and covered services. I can email it to you right now or it will come in your enrollment packet. Would you like me to send it?',
      'As part of this process, you should review the Summary of Benefits. It is the official document that has all the copays, benefits, and plan details in writing. Have you had a chance to look at it?',
    ],
    anti_patterns: [
      'You do not need to read the Summary of Benefits, I covered everything.',
      'The paperwork is just legal stuff, do not bother with it.',
      'Nobody actually reads those documents.',
    ],
  },
  {
    intent_code: 'PECL_013_STAR_RATINGS_PROVIDED',
    intent_name: 'Star ratings information provided',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent provides the plan CMS Star Rating so the beneficiary can understand the plan quality score.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.13',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 77,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'I also want to share the plan Star Rating with you. CMS rates every Medicare Advantage plan on a scale of 1 to 5 stars. This plan has a 4-star rating, which indicates above average quality.',
      'This plan currently has a 3.5-star rating from CMS. Star Ratings measure quality of care, member satisfaction, and other factors. You can look up ratings for any plan on Medicare.gov.',
      'For your information, the CMS Star Rating for this plan is 4.5 out of 5 stars. That is one of the highest-rated plans in your area.',
    ],
    anti_patterns: [
      'Star ratings do not really matter, they are all about the same.',
      'This plan has the best rating, trust me.',
      'I am not sure about the Star Rating but the plan is great.',
    ],
  },
  {
    intent_code: 'PECL_014_MULTI_LANGUAGE_INSERT',
    intent_name: 'Multi-language insert provided',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent informs the beneficiary about the availability of plan materials in other languages and the multi-language insert.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.14',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 78,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'I also want to let you know that plan materials are available in other languages. If you or someone you know would prefer materials in Spanish, Chinese, or another language, we can arrange that.',
      'Your enrollment packet will include a multi-language insert that explains how to request plan information in other languages. If you need materials in any language other than English, please let us know.',
      'Just so you are aware, this plan provides a multi-language insert with your materials. If English is not your preferred language, the plan can provide documents and assistance in other languages.',
    ],
    anti_patterns: [
      'The materials only come in English.',
      'You speak English so we do not need to worry about that.',
      'Other languages are not available for this plan.',
    ],
  },
  {
    intent_code: 'PECL_015_ENROLLMENT_FORM_EXPLAINED',
    intent_name: 'Enrollment form explained',
    category: 'PRE_ENROLLMENT_CHECKLIST',
    subcategory: null,
    description:
      'Agent explains the enrollment form, what information is needed, and how the enrollment process will be completed.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 3, Sec. 110.15',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: true,
    sequence_group: 'PRE_ENROLLMENT_CHECKLIST',
    sequence_position: 79,
    must_precede: [],
    must_follow: ['PECL_001_CHECKLIST_REFERENCED'],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'Now let me explain how the enrollment form works. I will need some personal information from you, including your Medicare number, and we will complete the enrollment application together over the phone.',
      'If you decide to move forward, we will fill out the enrollment application together. I will ask you a series of questions and enter the information into the form on your behalf. You will then give verbal consent to submit it.',
      'The enrollment form requires your name, address, date of birth, Medicare number, and a few other details. I will walk you through each section and you will confirm everything before we submit.',
      'Let me explain the enrollment process. We will complete the CMS enrollment form together. I will read each section to you, collect the required information, and you will verbally authorize the submission.',
    ],
    anti_patterns: [
      'Just give me your Medicare number and I will take care of everything.',
      'I already filled out the form for you, I just need you to say yes.',
      'We do not need to go through the form, I have all your information already.',
    ],
  },
];
