export const salesConduct = [
  {
    intent_code: 'CONDUCT_001_NO_CROSS_SELLING',
    intent_name: 'No cross-selling of non-health products',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent does not cross-sell non-health-related insurance products such as annuities, life insurance, or financial products during a Medicare Advantage enrollment call.',
    cms_reference: '42 CFR 422.2274(c)',
    mcmg_section: 'Ch. 2, Sec. 60.1',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: false,
    sample_phrases: [
      'Today we are going to focus exclusively on your Medicare Advantage options.',
      'My role today is to help you with your Medicare coverage and nothing else.',
      'We are here to discuss Medicare Advantage plans that fit your healthcare needs.',
      'I am only authorized to discuss Medicare-related products on this call.',
    ],
    anti_patterns: [
      'While we are at it, have you thought about a life insurance policy?',
      'I also sell annuities that pair well with your Medicare plan.',
      'Let me tell you about our final expense insurance since we are already talking.',
    ],
  },
  {
    intent_code: 'CONDUCT_002_NO_STEERING',
    intent_name: 'No steering toward specific plans without justification',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent does not steer the beneficiary toward a specific plan based on agent compensation or preference rather than the beneficiary actual needs.',
    cms_reference: '42 CFR 422.2274(c)',
    mcmg_section: 'Ch. 2, Sec. 60.2',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: false,
    sample_phrases: [
      'Based on the healthcare needs you described, I think this plan is the best fit because it covers your doctors and medications at the lowest cost to you.',
      'I am recommending this plan specifically because it matches what you told me about your priorities, the low specialist copays and the $0 drug coverage for your medications.',
      'Let me show you a few options and explain why each one might or might not be a good fit for your specific situation.',
      'I want to present several plans that meet your needs so you can compare them and make an informed choice.',
    ],
    anti_patterns: [
      'This is the plan I always recommend to everyone.',
      'Trust me, this is the only plan worth looking at.',
      'I am going to put you in the plan that makes the most sense.',
    ],
  },
  {
    intent_code: 'CONDUCT_003_NO_CHERRY_PICKING',
    intent_name: 'No health status discrimination or cherry-picking',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent does not discriminate against beneficiaries based on health status, pre-existing conditions, or disability. Agent does not discourage enrollment based on the beneficiary health conditions.',
    cms_reference: '42 CFR 422.110',
    mcmg_section: 'Ch. 2, Sec. 60.5',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: false,
    sample_phrases: [
      'Medicare Advantage plans cannot deny you coverage based on your health conditions. Everyone who is eligible can enroll regardless of their health status.',
      'Your pre-existing conditions will not prevent you from enrolling. Medicare Advantage plans are guaranteed issue during the enrollment period.',
      'It does not matter what health conditions you have, if you are eligible for Medicare, you can enroll in any plan available in your area.',
      'I want to assure you that this plan covers all of your conditions. No one can be turned away based on their health.',
    ],
    anti_patterns: [
      'With your health problems, this plan might not be the best idea.',
      'Honestly, someone as healthy as you does not really need all these benefits.',
      'I am not sure a plan with this much coverage makes sense for someone in your condition.',
    ],
  },
  {
    intent_code: 'CONDUCT_004_NO_MISLEADING_LANGUAGE',
    intent_name: 'No misleading or deceptive language used',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent does not use misleading, deceptive, or confusing language that could cause the beneficiary to misunderstand plan benefits, costs, or enrollment terms.',
    cms_reference: '42 CFR 422.2274(c)',
    mcmg_section: 'Ch. 2, Sec. 60.6',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: false,
    sample_phrases: [
      'I want to be very straightforward with you about what this plan does and does not cover so you can make an informed decision.',
      'Let me explain this benefit clearly. The dental coverage includes two cleanings per year and up to $1,500 in comprehensive dental services. Anything beyond that, you would be responsible for.',
      'I want to make sure I am clear, the $0 premium does not mean everything is free. You will still have copays and coinsurance when you use services.',
      'To be transparent, there are some limitations with this plan that I want you to understand before we go any further.',
    ],
    anti_patterns: [
      'This plan is basically free healthcare.',
      'You will never have to pay for anything with this plan.',
      'The government is paying for everything, this is your tax dollars at work.',
    ],
  },
  {
    intent_code: 'CONDUCT_005_NO_SCOPE_CREEP',
    intent_name: 'Stays within Scope of Appointment',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent stays within the product types authorized by the Scope of Appointment and does not discuss plans or products not included in the SOA.',
    cms_reference: '42 CFR 422.2274(b)',
    mcmg_section: 'Ch. 2, Sec. 40.3',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: false,
    sample_phrases: [
      'Your Scope of Appointment authorizes us to discuss Medicare Advantage plans today, so that is what we will focus on.',
      'We agreed to talk about Medicare Advantage options today. If you are interested in other products like Part D standalone plans, we would need to set up a separate appointment.',
      'Based on the scope you signed, I am authorized to go over MA plans with you. I want to stay within those boundaries.',
      'Our appointment today covers Medicare Advantage plans only. If you would like to explore other Medicare options, I would need a new SOA from you.',
    ],
    anti_patterns: [
      'While I have you, let me also tell you about this standalone drug plan.',
      'I know we said MA only, but you really should hear about this dental plan too.',
      'Your SOA just said Medicare, so that means I can talk about everything Medicare related.',
    ],
  },
  {
    intent_code: 'CONDUCT_006_PROFESSIONAL_TONE',
    intent_name: 'Maintains professional and respectful tone',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent maintains a professional, respectful, and courteous tone throughout the entire call, treating the beneficiary with dignity.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 60.7',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'I appreciate you taking the time to speak with me today. I want to make sure we find the right plan for you.',
      'That is a great question and I am happy to explain that in more detail.',
      'I completely understand your concern. Let me address that for you.',
      'Thank you for your patience while I look that up for you. I want to make sure I give you the correct information.',
    ],
    anti_patterns: [
      'Look, I have already explained this to you.',
      'That is a silly question, everyone knows that.',
      'Come on, we need to move this along.',
    ],
  },
  {
    intent_code: 'CONDUCT_007_PATIENCE_WITH_QUESTIONS',
    intent_name: 'Patient with beneficiary questions',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent demonstrates patience when the beneficiary asks questions, needs information repeated, or takes time to process information.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 60.8',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'Absolutely, I am happy to go over that again. There is no rush here.',
      'Of course, let me explain that one more time using a different example.',
      'No problem at all. I want to make sure you fully understand everything before moving forward.',
      'Please, take your time. I am here to answer any and all of your questions.',
      'That is a perfectly reasonable question. Let me walk through it step by step.',
    ],
    anti_patterns: [
      'I already told you that. Were you not listening?',
      'We really need to keep moving, I have other calls.',
      'I do not have time to go through this again.',
    ],
  },
  {
    intent_code: 'CONDUCT_008_NO_RUSHING',
    intent_name: 'Does not rush the beneficiary',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent does not rush the beneficiary through the call, the enrollment process, or any required disclosures. The beneficiary is given adequate time to process and respond.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 60.9',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'Take all the time you need. I want to make sure you are comfortable with everything before we move on.',
      'There is no time limit on this call. I am here for as long as you need me.',
      'Would you like me to pause for a moment so you can think that over?',
      'I know this is a lot of information. Let me slow down and we can go through it at your pace.',
    ],
    anti_patterns: [
      'We really need to speed this up, I have a tight schedule.',
      'Let me just run through these last few items real quick.',
      'Can we skip ahead? I am sure you get the idea.',
    ],
  },
  {
    intent_code: 'CONDUCT_009_ACCURATE_INFORMATION',
    intent_name: 'All information provided is accurate',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent provides only accurate and truthful information about plan benefits, costs, network, and enrollment terms. No fabricated or unverified claims.',
    cms_reference: '42 CFR 422.2274(c)',
    mcmg_section: 'Ch. 2, Sec. 60.10',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: false,
    sample_phrases: [
      'Let me pull up the exact copay for that service so I can give you the accurate number. I do not want to guess.',
      'According to the plan documentation, your specialist copay is $40 for in-network visits.',
      'I want to make sure I give you the correct information, so let me verify that in the plan details before I answer.',
      'That is a great question. Rather than guessing, let me look that up in the Summary of Benefits so I can give you the exact figure.',
    ],
    anti_patterns: [
      'I think the copay is around $20 or so, something like that.',
      'The plan covers pretty much everything you can think of.',
      'I am not sure about that but I would not worry about it.',
    ],
  },
  {
    intent_code: 'CONDUCT_010_NO_GUARANTEES',
    intent_name: 'No coverage guarantees made',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent does not guarantee specific coverage outcomes, approval of services, or that benefits will remain unchanged in future plan years.',
    cms_reference: '42 CFR 422.2274(c)',
    mcmg_section: 'Ch. 2, Sec. 60.11',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: false,
    sample_phrases: [
      'I cannot guarantee that a specific procedure will be approved, but based on the plan documentation, that type of service is generally covered.',
      'Keep in mind that plan benefits can change from year to year. What I am showing you today is for the current plan year.',
      'Coverage for certain services may require prior authorization, so I cannot promise it will be approved automatically.',
      'While this plan currently offers that benefit, I want you to know that plans can be updated annually and benefits may change in future years.',
    ],
    anti_patterns: [
      'I guarantee this plan will cover your surgery.',
      'These benefits will never change, you are locked in.',
      'I promise you will never pay more than what I am telling you today.',
    ],
  },
  {
    intent_code: 'CONDUCT_011_NO_SAVINGS_CLAIMS',
    intent_name: 'No unsubstantiated savings claims',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent does not make unsubstantiated or exaggerated claims about how much money the beneficiary will save by enrolling in the plan.',
    cms_reference: '42 CFR 422.2274(c)',
    mcmg_section: 'Ch. 2, Sec. 60.12',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'critical',
    auto_fail: false,
    sample_phrases: [
      'Based on the copays and premiums we discussed, this plan could potentially lower your monthly costs compared to what you are paying now, but your actual costs will depend on what services you use.',
      'I do not want to promise specific savings because your out-of-pocket costs will depend on your healthcare usage during the year.',
      'Comparing the premiums, this plan is $30 less per month than what you told me you are paying now. But keep in mind, total costs depend on how much care you need.',
      'Rather than quoting savings, let me walk you through the actual costs so you can compare them side by side with your current plan.',
    ],
    anti_patterns: [
      'You will save thousands of dollars with this plan.',
      'This plan will cut your healthcare costs in half.',
      'Everyone who switches saves at least $200 a month.',
    ],
  },
  {
    intent_code: 'CONDUCT_012_CARRIER_NAMES_12PT',
    intent_name: 'Carrier name mentioned when referencing plan',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent always uses the carrier or plan sponsor name when referencing or discussing a specific plan, rather than using generic terms.',
    cms_reference: '42 CFR 422.2268',
    mcmg_section: 'Ch. 2, Sec. 60.13',
    product_type: 'MA',
    is_required: true,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'moderate',
    auto_fail: false,
    sample_phrases: [
      'The Humana Gold Plus plan includes dental and vision coverage as well.',
      'With the Aetna Medicare Eagle Plus, your specialist copay would be $35.',
      'The UnitedHealthcare plan we are looking at has a $0 premium and includes Part D drug coverage.',
      'Under the Wellcare Giveback plan, you would receive a Part B premium reduction of $75 per month.',
    ],
    anti_patterns: [
      'This Medicare plan has great dental benefits.',
      'The plan we are looking at covers your drugs.',
      'One of our plans gives you money back on your Part B premium.',
    ],
  },
  {
    intent_code: 'CONDUCT_013_NO_COMPARISON_BY_NAME',
    intent_name: 'No plan comparison by carrier name without consent',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'Agent does not negatively compare plans by naming competing carriers or disparaging other companies without the beneficiary requesting such a comparison.',
    cms_reference: '42 CFR 422.2274(c)',
    mcmg_section: 'Ch. 2, Sec. 60.14',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'I can compare the benefits of the plans we have discussed if you would like. Would you like me to go over how they differ?',
      'Since you asked about how this plan compares to your current Humana plan, let me walk through the differences in benefits and costs.',
      'Rather than comparing carriers, let me focus on how this specific plan meets the needs you described.',
      'I would be happy to compare the plans side by side if that would be helpful. Shall I do that?',
    ],
    anti_patterns: [
      'The Humana plan is terrible compared to what I am showing you.',
      'UnitedHealthcare always has the worst customer service.',
      'Stay away from Aetna, their plans are never any good.',
    ],
  },
  {
    intent_code: 'CONDUCT_014_BENEFICIARY_CONFUSION',
    intent_name: 'Detects beneficiary confusion',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'System detects signs that the beneficiary is confused, uncertain, or does not understand what is being presented, including hesitation, conflicting responses, or expressions of confusion.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 60.15',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'It sounds like you might have some questions about what I just explained. Would you like me to go over it again?',
      'I want to make sure I am being clear. Would it help if I explained that in a different way?',
      'I noticed some hesitation. Is there something you would like me to clarify before we continue?',
      'I can tell this is a lot of information. Let me slow down and make sure we are on the same page.',
    ],
    anti_patterns: [
      'Let us just keep going, we are almost done.',
      'It is not that complicated, just say yes.',
      'Everyone gets confused by this part, do not worry about it.',
    ],
  },
  {
    intent_code: 'CONDUCT_015_AGENT_CLARIFIES_CONFUSION',
    intent_name: 'Agent addresses and clarifies confusion',
    category: 'SALES_CONDUCT',
    subcategory: null,
    description:
      'When the beneficiary expresses or exhibits confusion, the agent takes appropriate action to clarify the information, re-explain concepts, or offer to revisit topics.',
    cms_reference: '42 CFR 422.2274',
    mcmg_section: 'Ch. 2, Sec. 60.16',
    product_type: 'MA',
    is_required: false,
    is_sequence_sensitive: false,
    sequence_group: null,
    sequence_position: null,
    must_precede: [],
    must_follow: [],
    detection_type: 'intent',
    weight: 1.0,
    failure_severity: 'major',
    auto_fail: false,
    sample_phrases: [
      'Let me try explaining that differently. The maximum out-of-pocket is basically a safety net, it is the most you would ever pay in a year. After you hit that number, the plan pays everything.',
      'I understand that can be confusing. Think of the deductible like this, it is the amount you pay before the plan starts sharing costs with you.',
      'Let me go back to the network question since you seemed unsure. An HMO means you pick a primary doctor and they coordinate your care. You need a referral to see a specialist.',
      'I can see that was not clear. Let me start over on that part. The Part B giveback means the plan actually pays part of your Medicare Part B premium back to you each month.',
      'No worries at all. Let me break that down in simpler terms so it makes more sense.',
    ],
    anti_patterns: [
      'I already explained that, let us move on.',
      'You will figure it out when you get the paperwork.',
      'It is too complicated to explain again, just trust me.',
    ],
  },
];
