import React, { useCallback } from "react";
import { useScript } from "../context/ScriptContext";
import { generateSessionSummary } from "../context/scriptReducer";

export default React.memo(function SessionSummary() {
  const { state } = useScript();

  const handleExport = useCallback(() => {
    const summary = generateSessionSummary(state);

    const lines = [
      "═══════════════════════════════════════════════",
      "       ENROLLGEN — SESSION SUMMARY",
      "═══════════════════════════════════════════════",
      "",
      `Agent Name:          ${summary.agentName}`,
      `Session Start:       ${summary.sessionStart}`,
      `Session End:         ${summary.sessionEnd}`,
      "",
      "── ENROLLMENT DETAILS ──────────────────────────",
      `Plan Name:           ${summary.planName}`,
      `Effective Date:      ${summary.effectiveDate}`,
      `Enrollment Code:     ${summary.enrollmentCode}`,
      `Confirmation #:      ${summary.confirmationNumber}`,
      `SNP Type:            ${summary.snpType}`,
      "",
      "── SECTIONS COMPLETED ─────────────────────────",
    ];

    for (const s of summary.sections) {
      const status = s.completed ? "✓" : "✗";
      lines.push(`  ${status}  ${s.section.padEnd(32)} ${s.duration}`);
    }

    lines.push("");
    lines.push("── OPTIONAL PRODUCTS ──────────────────────────");
    lines.push(
      `  Hospital Indemnity:  ${summary.optionalProducts.hospitalIndemnity}`
    );
    lines.push(
      `  Dental & Vision:     ${summary.optionalProducts.dentalVision}`
    );
    lines.push(
      `  Final Expense:       ${summary.optionalProducts.finalExpense}`
    );
    lines.push("");
    lines.push("═══════════════════════════════════════════════");
    lines.push("  Generated by EnrollGen — Local session only");
    lines.push("═══════════════════════════════════════════════");

    const text = lines.join("\n");

    // Create download
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const ts = new Date().toISOString().slice(0, 10);
    const agentSlug = (state.agentName || "agent")
      .replace(/\s+/g, "_")
      .toLowerCase();
    a.download = `EnrollGen_Summary_${agentSlug}_${ts}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [state]);

  const handleCopyToClipboard = useCallback(() => {
    const summary = generateSessionSummary(state);
    const lines = [
      `Agent: ${summary.agentName}`,
      `Plan: ${summary.planName}`,
      `Date: ${summary.effectiveDate}`,
      `Enrollment Code: ${summary.enrollmentCode}`,
      `Confirmation: ${summary.confirmationNumber}`,
      `SNP: ${summary.snpType}`,
      "",
      "Sections:",
    ];
    for (const s of summary.sections) {
      const status = s.completed ? "✓" : "✗";
      lines.push(`  ${status} ${s.section} (${s.duration})`);
    }
    navigator.clipboard.writeText(lines.join("\n"));
  }, [state]);

  // Only show after enrollment is submitted
  if (!state.enrollOk) return null;

  return (
    <div className="session-summary-bar">
      <span className="session-summary-label">
        📋 Session complete — export your records
      </span>
      <div className="session-summary-actions">
        <button className="primary" onClick={handleCopyToClipboard}>
          Copy Summary
        </button>
        <button className="primary" onClick={handleExport}>
          Download .txt
        </button>
      </div>
    </div>
  );
});
