export const MEDSUP_SECTIONS = [
  {
    id: "ms-1",
    num: 1,
    key: "recordingOk",
    label: "Recording Disclosure",
    script: [
      "Thank you for calling New Gen Health Solutions, this is [Agent Name]. Who am I speaking with today?",
      "Hi [First Name]. This call may be recorded and monitored for quality and compliance purposes. Is that okay?",
    ],
    gate: "Recording disclosure completed",
  },
  {
    id: "ms-2",
    num: 2,
    key: "tpmoOk",
    label: "TPMO Disclosure",
    compliance: true,
    script: [
      "We do not offer every plan available in your area. Any information we provide is limited to those plans we do offer. Please contact Medicare.gov or 1-800-MEDICARE to get information on all of your options.",
    ],
    gate: "TPMO disclosure completed",
  },
  {
    id: "ms-3",
    num: 3,
    key: "qualOk",
    label: "Qualification",
    script: [
      "How old are you, and do you have both Medicare Part A and Part B?",
      "What state do you live in?",
      "Are you currently on a Medicare Supplement plan, a Medicare Advantage plan, or Original Medicare only?",
    ],
    gate: "Qualification completed",
  },
  {
    id: "ms-4",
    num: 4,
    key: "discoveryOk",
    label: "Discovery",
    script: [
      "What plan letter do you have now, if you know it?",
      "Who is your current carrier?",
      "What are you paying per month?",
      "To check if you can qualify for a lower rate, I need to ask a few health questions. Is that okay?",
      "In the past two years, have you had any hospitalizations, major surgeries, or serious conditions like cancer, heart disease, COPD, or kidney disease?",
    ],
    gate: "Discovery completed",
  },
  {
    id: "ms-5",
    num: 5,
    key: "quoteOk",
    label: "Quote Transition",
    script: [
      "Based on what you told me, I may have an option with the same plan letter at a lower monthly premium.",
      "Right now you have [PLAN LETTER] with [CURRENT CARRIER] at [CURRENT PREMIUM].",
      "I am showing [PLAN LETTER] with [NEW CARRIER] at about [QUOTED PREMIUM].",
      "That is a difference of about [DIFFERENCE] per month, or [ANNUAL SAVINGS] per year.",
      "Same plan letter means the benefits stay the same. The main difference is the carrier and premium.",
    ],
    gate: "Quote transition completed",
  },
  {
    id: "ms-6",
    num: 6,
    key: "enrollOk",
    label: "Close / Enrollment",
    script: [
      "Would you like to move forward with the application?",
      "I will walk you through it. Do you have your Medicare card with you?",
      "The application will include standard health questions, and [CARRIER] may contact you to verify information.",
      "Your requested effective date would be [DATE].",
    ],
    gate: "Close and enrollment completed",
  },
  {
    id: "ms-7",
    num: 7,
    key: "wrapOk",
    label: "Wrap Up",
    compliance: true,
    script: [
      "To recap, we reviewed your current coverage, discussed your options, and the next step is [NEXT STEP]. Does that sound right?",
      "We do not offer every plan available in your area. Any information we provide is limited to those plans we do offer. Please contact Medicare.gov or 1-800-MEDICARE to get information on all of your options.",
      "Thank you for calling New Gen Health Solutions.",
    ],
    gate: "Wrap up completed",
  },
];
