-- ============================================================
-- TENANT SCRIPT TEMPLATES
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.script_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
  flow_type TEXT NOT NULL CHECK (flow_type IN ('ma', 'medsup', 'aca', 'u65', 'ancillary')),
  version INTEGER NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT true,
  sections JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (tenant_id, flow_type, version)
);

CREATE INDEX IF NOT EXISTS idx_script_templates_tenant_flow
  ON public.script_templates(tenant_id, flow_type, is_active, version DESC);

DROP TRIGGER IF EXISTS script_templates_set_updated_at ON public.script_templates;
CREATE TRIGGER script_templates_set_updated_at
  BEFORE UPDATE ON public.script_templates
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.script_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "script_templates_tenant_access" ON public.script_templates;
CREATE POLICY "script_templates_tenant_access"
  ON public.script_templates FOR SELECT TO authenticated
  USING (tenant_id IS NULL OR public.is_current_tenant(tenant_id));

DROP POLICY IF EXISTS "script_templates_tenant_write" ON public.script_templates;
CREATE POLICY "script_templates_tenant_write"
  ON public.script_templates FOR INSERT TO authenticated
  WITH CHECK (tenant_id IS NOT NULL AND public.is_current_tenant(tenant_id));

DROP POLICY IF EXISTS "script_templates_tenant_update" ON public.script_templates;
CREATE POLICY "script_templates_tenant_update"
  ON public.script_templates FOR UPDATE TO authenticated
  USING (tenant_id IS NOT NULL AND public.is_current_tenant(tenant_id))
  WITH CHECK (tenant_id IS NOT NULL AND public.is_current_tenant(tenant_id));

DROP POLICY IF EXISTS "script_templates_service_role" ON public.script_templates;
CREATE POLICY "script_templates_service_role"
  ON public.script_templates FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

DO $$
DECLARE
  nghs_tenant UUID;
BEGIN
  SELECT id INTO nghs_tenant
  FROM public.tenants
  WHERE clerk_org_id = 'org_3DHzWeCe9QZ4zmAYXCmUpGnDwfQ'
     OR id = '00000000-0000-4000-8000-000000000001'::uuid
  ORDER BY CASE WHEN clerk_org_id = 'org_3DHzWeCe9QZ4zmAYXCmUpGnDwfQ' THEN 0 ELSE 1 END
  LIMIT 1;

  IF nghs_tenant IS NULL THEN
    RAISE NOTICE 'Skipping script template seed because NGHS tenant was not found.';
    RETURN;
  END IF;

  INSERT INTO public.script_templates (tenant_id, flow_type, version, is_active, sections)
  VALUES (
    nghs_tenant,
    'ma',
    1,
    true,
    $json$[
      {"key":"recording","section_number":1,"title":"Recording Disclosure","gate_field":"recordingOk","body":"\"Thank you for calling New Gen Health Solutions. My name is [First & Last Name]. I am a licensed sales agent on a recorded line. Who do I have the pleasure of speaking with?\" \"Please know our call will be recorded for quality and training purposes; is it ok if I continue?\" \"So (Client's Name), we are reaching out to review your current Medicare coverage and see if you may qualify for a Special Enrollment Period, because provider networks, prescription costs, and plan benefits can change during the year. I want to make sure your plan is still meeting your needs and review any benefits that may be available to you based on your eligibility and location.","compliance_locked":true,"sort_order":1,"verbatim":true,"lock_message":"Complete Recording Disclosure to continue."},
      {"key":"tpmo","section_number":2,"title":"TPMO Disclaimer & Federal Contracting Statement","gate_field":"tpmoOk","body":"\"Can I please have your Zipcode?\" \"May I have your First and Last Name\" \"May I have a phone number to call you back?\"\n\n\"We do not offer every plan available in your area. Currently we represent [number of organizations] organizations which offer [number of plans] products in your area. Please contact Medicare.gov, 1-800-MEDICARE, or your local State Health Insurance Program (SHIP) to get information on all of your options. Plans are insured or covered by a Medicare Advantage (HMO, PPO, PFFS) organization with a Medicare contract and/or a Medicare-approved Part D sponsor. Enrollment in the plan depends on the plan's contract renewal with Medicare.\"","compliance_locked":true,"sort_order":2,"verbatim":true,"lock_message":"Complete TPMO to continue."},
      {"key":"soa","section_number":3,"title":"Power of Attorney & Scope of Appointment","gate_field":"soaOk","body":"\"Are you interested in discussing Medicare options for yourself or for someone else, such as a family member, guardian or someone that you are authorized to make decisions for?\"  (IF YES): \"Are they available now or should we discuss at a later time when they are available?\"\n\n\"You are not obligated to enroll in a plan and agreeing to answer these questions does not affect your current enrollment nor will it enroll you in any Medicare Advantage Prescription Drug Plan, or other Medicare Plan. Do I have your permission to discuss the plans in your area which may include Medicare Advantage plans, Prescription drug plans, and other types of plans like Stand-alone Dental plan, Stand-alone Vision plans, and Hospital Indemnity Plans today?\"","compliance_locked":true,"sort_order":3,"verbatim":true,"lock_message":"SOA required before Needs Assessment."},
      {"key":"qualifications","section_number":4,"title":"Qualifications","gate_field":"qualOk","body":"\"Do you have or will soon have Medicare Parts A and B?\"\nIf yes: \"Can you please grab your Red, White and Blue Medicare card\"\nIf not available: Verify full legal name, date of birth, and Social Security Number. (Agent note: Send to MARx check.)\n\"Can you tell me what it says on your card for the Part A and Part B effective dates?\" (Read back effective dates)\n\"Are you currently receiving any assistance with your Part B premium through Medicaid, or help for prescription coverage?\"\n\"Do you mind confirming your permanent home address?\"\n\"Are you a veteran?\" (If yes: Thank them for their service!)\n\"Do you currently have other coverage such as employer coverage, retiree benefits, VA benefits, TRICARE for Life, or CHAMPVA?\"\n(Agent note: If present, politely end the call. Basic VA coverage alone may proceed.)\n\"In the last twelve months, have you gone to an emergency room or an urgent care center for medical care?\" (IF YES): \"Was that one or two times, or more than that?\"\n\n(AEP) \"The Annual Election Period runs from October 15 through December 7. We are currently within this period, so you may make a Medicare plan change.\"\n(OE / MA-OEP) \"Medicare Open Enrollment runs from January 1 through March 31. Since we are within this period, you may make a one-time plan change.\"\n(SEP) \"You qualify for a Special Election Period, which allows you to make a Medicare plan change outside of the standard enrollment periods.\"","compliance_locked":false,"sort_order":4,"verbatim":true,"lock_message":"Qualifications must be completed before proceeding to Needs Assessment."},
      {"key":"neads","section_number":5,"title":"NEADS Assessment","gate_field":"neadsOk","body":"\"I am going to ask you a few quick questions to make sure I find the best plan for your needs.\"\n\"Who is your current primary care physician?\" (Confirm location)\n\"Do you see any specialists? If so, who?\" (Confirm location)\n\"Is there a particular hospital or facility you want to make sure is covered?\"\n\"What medications do you take regularly?\" (Confirm medications if already populated in Sunfire. Confirm full name & doseage)\n\"Which pharmacy do you use?\"\n\"Is there anything specific about your current plan that you want to make sure your new plan has?\"\n*Review Provider network status for PCP and specialists\n*Review Prescription drug coverage and costs\n*Review Plan premiums and Part B premium\n\"Let me summarize what we've covered. Does that sound right? Anything else I should know before we look at plans?\"\n\"Some people also ask about dental, vision, or final expense coverage. We can touch on that after we finish your Medicare if you're interested.\" (CHECK DENTAL AND FINAL EXPENSE BUTTONS AFTER ENROLLMENT)","compliance_locked":false,"sort_order":5,"verbatim":true,"lock_message":"Locked until Qualifications are complete."},
      {"key":"sob","section_number":6,"title":"Plan Selection & Summary of Benefits","gate_field":"sobOk","body":"\"Based on your doctors, prescriptions, and what you told me matters most, [Plan Name] looks like a good option for you.\"\n\"Here are the benefits of the plan.\" (List benefits in SOB)\n\n\"Do you have any questions about the benefits we just reviewed?\"\n\"You will receive your Summary of Benefits and Evidence of Coverage in the mail or by email if chosen during enrollment. The Evidence of Coverage is a detailed explanation of all services covered by the carrier.\"\n\"You have the right to cancel your plan at any time before the effective date by calling the carrier directly. I will give you that number at the end of this call.\" If you are ready to enroll, we will move to the enrollment process now.\"\n\nPart B Premium Reduction Applies:\n\"This plan includes a Part B premium reduction. There may be a delay - it can take one or more payment cycles to take effect.\"\n\"If your Part B premium comes out of Social Security, the reduction will show as an increase in your Social Security payment. If you pay Part B directly, you will receive a credit on your statement.\"\n\"Your Part B premium reduction for this plan is [amount], however that may change based on the amount you pay for Part B.\"","compliance_locked":false,"sort_order":6,"verbatim":true,"lock_message":"Locked until NEADS is complete."},
      {"key":"enrollment","section_number":7,"title":"Enrollment","gate_field":"enrollOk","body":"\"I can enroll you today over the telephone in this [plan name with plan code]. Enrolling in this plan will replace your current [coverage type]. Once approved by Medicare, your new coverage begins on [effective date]. Would you like to proceed?\"\n(Complete enrollment on Sunfire and read all disclosures)\n\n\"Your enrollment application has been successfully submitted. Your application number is [application ID#].\"\n\"[Carrier]'s Customer Service number is [phone and TTY].\"\n\"Your proposed effective date is [effective date], subject to approval by Medicare.\"\n\"You will receive a notice in the mail acknowledging your enrollment. Plan materials and your member ID card should arrive within 7 to 10 business days, but no later than 10 days before your effective date. You can also access materials online at [carrier URL].\"\n\"If you have any questions or your needs change, you can reach us at [EnrollHere number] or our office at [office number].\"\n\nLocal note fields: Carrier, Plan Name, Plan ID, Effective Date, Enrollment / Application ID.\nPre-enrollment checklist verifies Recording Disclosure, TPMO Disclaimer, Scope of Appointment, Qualifications, NEADS Assessment, Plan Selection & SOB, and Plan Name before submission.","compliance_locked":true,"sort_order":7,"verbatim":true,"lock_message":"Locked until SOB Review is complete."},
      {"key":"wrapup","section_number":8,"title":"Wrap-Up","gate_field":null,"body":"\"Great news, your Medicare enrollment is all set.\"\n\nCall closing: \"It's been a pleasure speaking with you today. If you have any family members or friends that would benefit by speaking with me, please give them my number and I would be happy to assist them too.\"\nEnd the call: \"Thank you for [calling/choosing] [Carrier name] and have a great day!\"\n\nPost-call intake fields: Customer First Name, Customer Last Name, Phone, Call Outcome, Date of Birth, Email, State, MBI / Member ID, Medicaid, Medicaid Number, Previous Carrier, New Carrier, Plan Name, Plan ID, Plan / Enrollment Code, Monthly Premium, Sunfire Code, Effective Date, 60 Day Follow-Up Date, Confirmation Number, SEP, Agency, Writing Agent, HRA Completed, HRA Date, Agent Notes.","compliance_locked":false,"sort_order":8,"verbatim":true,"lock_message":""}
    ]$json$::jsonb
  )
  ON CONFLICT (tenant_id, flow_type, version) DO UPDATE SET
    is_active = EXCLUDED.is_active,
    sections = EXCLUDED.sections,
    updated_at = now();

  INSERT INTO public.script_templates (tenant_id, flow_type, version, is_active, sections)
  VALUES (
    nghs_tenant,
    'medsup',
    1,
    true,
    $json$[
      {"key":"recordingOk","section_number":1,"title":"Recording Disclosure","gate_field":"recordingOk","body":"Thank you for calling New Gen Health Solutions, this is [Agent Name]. Who am I speaking with today?\nHi [First Name]. This call may be recorded and monitored for quality and compliance purposes. Is that okay?","compliance_locked":false,"sort_order":1,"verbatim":true,"lock_message":"Recording disclosure completed"},
      {"key":"tpmoOk","section_number":2,"title":"TPMO Disclosure","gate_field":"tpmoOk","body":"We do not offer every plan available in your area. Any information we provide is limited to those plans we do offer. Please contact Medicare.gov or 1-800-MEDICARE to get information on all of your options.","compliance_locked":true,"sort_order":2,"verbatim":true,"lock_message":"TPMO disclosure completed"},
      {"key":"qualOk","section_number":3,"title":"Qualification","gate_field":"qualOk","body":"How old are you, and do you have both Medicare Part A and Part B?\nWhat state do you live in?\nAre you currently on a Medicare Supplement plan, a Medicare Advantage plan, or Original Medicare only?","compliance_locked":false,"sort_order":3,"verbatim":true,"lock_message":"Qualification completed"},
      {"key":"discoveryOk","section_number":4,"title":"Discovery","gate_field":"discoveryOk","body":"What plan letter do you have now, if you know it?\nWho is your current carrier?\nWhat are you paying per month?\nTo check if you can qualify for a lower rate, I need to ask a few health questions. Is that okay?\nIn the past two years, have you had any hospitalizations, major surgeries, or serious conditions like cancer, heart disease, COPD, or kidney disease?","compliance_locked":false,"sort_order":4,"verbatim":true,"lock_message":"Discovery completed"},
      {"key":"quoteOk","section_number":5,"title":"Quote Transition","gate_field":"quoteOk","body":"Based on what you told me, I may have an option with the same plan letter at a lower monthly premium.\nRight now you have [PLAN LETTER] with [CURRENT CARRIER] at [CURRENT PREMIUM].\nI am showing [PLAN LETTER] with [NEW CARRIER] at about [QUOTED PREMIUM].\nThat is a difference of about [DIFFERENCE] per month, or [ANNUAL SAVINGS] per year.\nSame plan letter means the benefits stay the same. The main difference is the carrier and premium.","compliance_locked":false,"sort_order":5,"verbatim":true,"lock_message":"Quote transition completed"},
      {"key":"enrollOk","section_number":6,"title":"Close / Enrollment","gate_field":"enrollOk","body":"Would you like to move forward with the application?\nI will walk you through it. Do you have your Medicare card with you?\nThe application will include standard health questions, and [CARRIER] may contact you to verify information.\nYour requested effective date would be [DATE].","compliance_locked":false,"sort_order":6,"verbatim":true,"lock_message":"Close and enrollment completed"},
      {"key":"wrapOk","section_number":7,"title":"Wrap Up","gate_field":"wrapOk","body":"To recap, we reviewed your current coverage, discussed your options, and the next step is [NEXT STEP]. Does that sound right?\nWe do not offer every plan available in your area. Any information we provide is limited to those plans we do offer. Please contact Medicare.gov or 1-800-MEDICARE to get information on all of your options.\nThank you for calling New Gen Health Solutions.","compliance_locked":true,"sort_order":7,"verbatim":true,"lock_message":"Wrap up completed"}
    ]$json$::jsonb
  )
  ON CONFLICT (tenant_id, flow_type, version) DO UPDATE SET
    is_active = EXCLUDED.is_active,
    sections = EXCLUDED.sections,
    updated_at = now();

  INSERT INTO public.script_templates (tenant_id, flow_type, version, is_active, sections)
  VALUES (
    nghs_tenant,
    'aca',
    1,
    true,
    $json$[
      {"key":"state_gate0Ok","section_number":1,"title":"Opening & Coverage Screening","gate_field":"gate0Ok","body":"Hi, this is [Agent Name], licensed agent with New Gen Health Solutions.\nThe main purpose of this call is health insurance. There are a few qualifying questions I need to ask first. Let's get started.\nDo you currently have coverage through your employer, Medicaid, or anything like that?\nAgent note: Await the client's introduction before moving forward.\nAgent note: If the client says yes to employer coverage, Medicaid, or similar active coverage, stop this quoting flow instead of continuing.","compliance_locked":false,"sort_order":1,"verbatim":true,"lock_message":"Coverage screened and intro completed"},
      {"key":"state_gate1Ok","section_number":2,"title":"ZIP, DOB & Household","gate_field":"gate1Ok","body":"Perfect. To see what plans are available in your area, what is the ZIP code where you currently live?\nWhat is your date of birth?\nIs there anyone else in your household who needs this coverage as well, such as a spouse or children?\nAgent note: Verify the ZIP code and county before moving on.\nAgent note: Confirm the date of birth and note anyone else applying for coverage.","compliance_locked":false,"sort_order":2,"verbatim":true,"lock_message":"ZIP, county, DOB, and household captured"},
      {"key":"state_gate2Ok","section_number":3,"title":"Income & FPL Review","gate_field":"gate2Ok","body":"What is your estimated household income for 2025?\nIf you do have income, I can deduct up to 30% for taxes when I work up the quote.\nIf you are not working but looking for work, I can use the minimum income amount from the FPL chart so the quote can load today, but I need your agreement before I enter that amount.\nAgent note: Use the FPL tool below where the script references the chart.\nAgent note: The client must explicitly consent before you enter any minimum working income on the quote.","compliance_locked":false,"sort_order":3,"verbatim":true,"lock_message":"Income reviewed and FPL reference confirmed"},
      {"key":"state_gate3Ok","section_number":4,"title":"Doctors, Prescriptions & Household Needs","gate_field":"gate3Ok","body":"While these plans are loading, do you have any doctors, hospitals, or prescriptions you want me to check?\nI want to make sure your providers take these plans and your medications are covered as well.\nAgent note: Verify the spelling of all doctors, hospitals, and medications before comparing plans.\nAgent note: Keep the household members needing coverage tied to the quote you are building.","compliance_locked":false,"sort_order":4,"verbatim":true,"lock_message":"Providers and medications gathered"},
      {"key":"state_gate4Ok","section_number":5,"title":"Plan Review & Selection","gate_field":"gate4Ok","body":"Now that I have the best matches in front of me, let me compare the top plans for you.\nI will walk through the monthly premium, deductible, primary care copay, specialist copay, and prescription costs so you can see the difference clearly.\nAgent note: Compare the strongest plan options after provider and prescription checks are complete.\nAgent note: Keep the explanation focused on premium, deductible, PCP, specialist, and Rx costs.","compliance_locked":false,"sort_order":5,"verbatim":true,"lock_message":"Plans reviewed and direction selected"},
      {"key":"state_gate5Ok","section_number":6,"title":"Selection & Login Handoff","gate_field":"gate5Ok","body":"Once we pick the plan, click Login on the top right of the page to continue the application.\nBefore moving forward, confirm again which plan the client wants and that the pricing you reviewed is the plan they are selecting.\nAgent note: Use this gate as the handoff from quoting into the live application.\nAgent note: Do not move to login until the client clearly agrees with the selected plan.","compliance_locked":false,"sort_order":6,"verbatim":true,"lock_message":"Plan selected and login handoff ready"},
      {"key":"state_gate6Ok","section_number":7,"title":"Wrap-Up & Next Step","gate_field":"gate6Ok","body":"Let me recap the plan we selected and the next step before I move into the login screen.\nAfter login, I will continue the application with the information we verified on this call.\nAgent note: Use the recap to make sure the client understands the selected plan and the application is the next step.\nAgent note: Record any plan choice details before leaving the quote screen.","compliance_locked":false,"sort_order":7,"verbatim":true,"lock_message":"Recap complete and application ready"},
      {"key":"ffm_gate0Ok","section_number":8,"title":"FFM: Opening & Identity Verification","gate_field":"gate0Ok","body":"Hi, this is [Agent Name] with New Gen Health Solutions. Am I speaking with [Client Name]?\nGreat. I'm a licensed health insurance agent and Ill be helping you review your health coverage options. Before we get started, I need to let you know this call may be recorded for quality and compliance purposes. Is that okay?\nPerfect. Let me verify a few things. Can you confirm your full legal name and date of birth?\nAnd can you confirm your state and ZIP code?\nI also need to confirm whether youve had a recent qualifying life event that may make you eligible for coverage, such as losing other coverage, moving, getting married, or having a baby.\nAgent note: If consent is declined: explain recording is required per NGHS compliance policy and offer a secure online enrollment link instead.\nAgent note: On state capture: derive stateBased signal. If NJ or PA, flag state-based exchange (Get Covered NJ or PA Pennie).\nAgent note: Branch: If OEP -> set enrollmentPeriod to OEP, skip Gate 1. If SEP -> proceed to Gate 1.\nChecklist: Identity verified (name + DOB confirmed)\nChecklist: Call recording consent obtained","compliance_locked":false,"sort_order":8,"verbatim":true,"lock_message":"Identity verified - consent obtained - enrollment period determined"},
      {"key":"ffm_gate1Ok","section_number":9,"title":"FFM: SEP Qualification","gate_field":"gate1Ok","body":"You mentioned a qualifying life event. Can you tell me a little more about what happened?\nWhen exactly did that happen? I need to make sure we're still within the 60-day enrollment window.\nSEP type reference:\n- Loss of Coverage: termination letter, COBRA notice, or prior plan end date; 60 days from loss date\n- Marriage: marriage certificate; 60 days from marriage date\n- Birth or adoption: birth certificate or adoption decree; 60 days from birth/adoption date\n- Permanent move: proof of new address; 60 days from move date\n- Loss of Medicaid/CHIP: Medicaid termination notice; 60 days from termination\n- Income change above Medicaid threshold: pay stubs, tax return, or employment letter; 60 days from change\nAgent note: COMPLIANCE: If the SEP window has expired, do NOT proceed with marketplace enrollment. Inform client of the deadline and explore off-exchange alternatives.\nAgent note: If sepExpiringSoon is less than 7 days, prioritize enrollment completion today.\nChecklist: SEP qualifying event confirmed\nChecklist: SEP date within 60-day window verified\nChecklist: SEP documentation identified / noted","compliance_locked":false,"sort_order":9,"verbatim":true,"lock_message":"SEP event verified - within 60-day window"},
      {"key":"ffm_gate2Ok","section_number":10,"title":"FFM: Household & Income Assessment","gate_field":"gate2Ok","body":"Now I need to understand your household so we can figure out what kind of financial help you qualify for. How many people are in your tax household - that's you, your spouse if filing jointly, and any dependents you claim?\nAnd what's your estimated total household income for 2026? This includes wages, self-employment income, Social Security, investment income - basically your modified adjusted gross income.\nCompliance note: 2026 SUBSIDY CLIFF: Enhanced PTCs from ARP/IRA expired 12/31/2025. Clients above 400% FPL have NO subsidy. This is the #1 reason to have the U65 off-exchange flow ready as a pivot.\n[If subsidyEligible] Great news - based on what you've told me, you should qualify for a monthly tax credit of approximately $[estimatedAPTC] to lower your premium. That's applied automatically when we enroll.\n[If > 400% FPL] Based on your income, you won't qualify for a premium subsidy on the marketplace this year. The enhanced subsidies that were available the last few years expired at the end of 2025. We have two options: I can show you full-price marketplace plans, or I can walk you through some private off-exchange alternatives that might be more affordable. Which would you prefer?\nFPL / subsidy reference:\n- 0-138% FPL: Medicaid eligible in expansion states\n- 139-150% FPL: Max APTC + CSR; strongly recommend Silver plan\n- 151-200% FPL: High APTC + CSR; Silver is generally best value\n- 201-250% FPL: Moderate APTC + CSR; compare Silver to Bronze\n- 251-400% FPL: APTC available, no CSR; compare Bronze, Silver, Gold\n- > 400% FPL: no APTC in 2026; consider off-exchange alternatives\nChecklist: Household size documented\nChecklist: Income documented / estimated\nChecklist: FPL% calculated and subsidy eligibility determined","compliance_locked":false,"sort_order":10,"verbatim":true,"lock_message":"Household + income documented - subsidy eligibility determined"},
      {"key":"ffm_gate3Ok","section_number":11,"title":"FFM: Needs Analysis & Plan Preferences","gate_field":"gate3Ok","body":"Let me ask a few questions so I can narrow down the best plans for you.\nDo you have any doctors or specialists you need to keep seeing? If so, who are they and where are they located?\nAre you currently taking any prescription medications?\nHow would you describe your healthcare usage - are you pretty healthy and mostly need preventive care, or do you have ongoing conditions or expect any procedures this year?\nAnd what's your monthly budget for health insurance?\nMetal guidance:\n- Low utilization + budget-conscious + no CSR -> Bronze\n- Low utilization + CSR eligible -> Silver\n- Moderate utilization -> Silver\n- High utilization / chronic conditions -> Gold\n- Very low income + expansion state -> check Medicaid first\nChecklist: Provider preferences documented\nChecklist: Prescription list documented\nChecklist: Utilization level assessed\nChecklist: Budget range noted","compliance_locked":false,"sort_order":11,"verbatim":true,"lock_message":"Needs documented - metal level direction determined"},
      {"key":"ffm_gate4Ok","section_number":12,"title":"FFM: Plan Presentation & Selection","gate_field":"gate4Ok","body":"Based on everything you've told me, I've pulled up [2-3] plans that look like the best fit. Let me walk you through each one.\nPlan 1 is [Carrier] [Plan Name], a [Metal Level] plan. Your monthly premium after the tax credit would be approximately $[amount]. The deductible is $[amount], and your copay for a primary care visit is $[amount]. Specialist visits are $[amount].\n[If CSR eligible] Because of your income level, Silver plans come with extra cost-sharing reductions that lower your deductible and copays. That's why Silver is really the best value for you even if Bronze looks cheaper on premium alone.\nLet me check that your doctors are in-network on the plan you're leaning toward. [Verify provider directory]\nAnd let me check your prescriptions on the formulary. [Verify drug coverage]\nAgent note: COMPLIANCE: Never guarantee specific premium amounts until the application is processed. Use approximately or estimated language.\nChecklist: Plan benefits reviewed with client\nChecklist: Network adequacy checked for client providers\nChecklist: Formulary checked for client prescriptions\nChecklist: Premium amount disclosed with subsidy if applicable","compliance_locked":false,"sort_order":12,"verbatim":true,"lock_message":"Plan presented, network/formulary verified, plan selected"},
      {"key":"ffm_gate5Ok","section_number":13,"title":"FFM: Enrollment & Submission","gate_field":"gate5Ok","body":"Great choice. Let's get you enrolled. I'm going to walk you through the application now. I'll need some additional information.\nCan you confirm your Social Security Number? [Or application ID if already started]\nDo you want to apply the full estimated tax credit of $[estimatedAPTC] per month to lower your premium, or would you prefer to take a smaller amount now and get the rest as a refund at tax time?\nI'm submitting your enrollment now. [Process application]\nYour enrollment is confirmed. Your confirmation number is [number]. Your coverage effective date is [date]. Your first premium payment of $[amount] is due by [date].\nExchange note: Enrollment platform by state: NJ -> Get Covered NJ; PA -> PA Pennie; VA, GA -> Healthcare.gov\nAgent note: COMPLIANCE: SSN is collected within the exchange platform, NOT in EnrollGen or any NGHS system. Agent enters directly into the exchange enrollment portal.\nChecklist: APTC election amount confirmed\nChecklist: Enrollment submitted successfully\nChecklist: Confirmation number recorded\nChecklist: Effective date confirmed\nChecklist: First premium amount and due date disclosed","compliance_locked":false,"sort_order":13,"verbatim":true,"lock_message":"Enrollment submitted - confirmation number recorded"},
      {"key":"ffm_gate6Ok","section_number":14,"title":"FFM: Closing & Follow-Up","gate_field":"gate6Ok","body":"Let me recap what we set up today. You're enrolled in [Plan Name] with [Carrier]. Your monthly premium is $[amount] after the tax credit. Coverage starts [date]. You'll receive a welcome packet from [Carrier] with your ID card and instructions for setting up your online portal.\nA few important things: make sure you pay your first premium by [date] or your coverage won't activate. If you need to see a doctor before your ID card arrives, you can call [Carrier] member services for a temporary ID.\nI'm going to follow up with you in about two weeks to make sure everything is set up and you have your ID card. What's the best way to reach you?\nIs there anything else I can help you with today? [Pause] Great. Thank you for trusting New Gen Health Solutions with your health coverage. Have a great day!\nChecklist: Coverage recap provided to client\nChecklist: First premium payment instructions given\nChecklist: Follow-up scheduled\nChecklist: Client confirmed understanding of next steps","compliance_locked":false,"sort_order":14,"verbatim":true,"lock_message":"Call closed - follow-up scheduled"}
    ]$json$::jsonb
  )
  ON CONFLICT (tenant_id, flow_type, version) DO UPDATE SET
    is_active = EXCLUDED.is_active,
    sections = EXCLUDED.sections,
    updated_at = now();

  INSERT INTO public.script_templates (tenant_id, flow_type, version, is_active, sections)
  VALUES (
    nghs_tenant,
    'u65',
    1,
    true,
    $json$[
      {"key":"gate0Ok","section_number":1,"title":"Opening","gate_field":"gate0Ok","body":"\"Hi, this is [Agent Name] with New Gen Health Solutions. Am I speaking with [Client Name]? I'm a licensed health insurance agent. I understand you're looking for health coverage options. This call may be recorded for quality and compliance purposes - is that okay?\"","compliance_locked":false,"sort_order":1,"verbatim":true,"lock_message":"Opening complete"},
      {"key":"gate1Ok","section_number":2,"title":"Situation Assessment","gate_field":"gate1Ok","body":"\"Tell me about your situation - what kind of coverage do you have right now, if any? Are you self-employed, W-2, or somewhere in between? Have you looked at marketplace plans yet, and what was the pricing like?\"","compliance_locked":false,"sort_order":2,"verbatim":true,"lock_message":"Situation assessed"},
      {"key":"gate2Ok","section_number":3,"title":"Health Profile","gate_field":"gate2Ok","body":"\"I need to ask a few health questions to figure out which products fit. How would you describe your overall health? Are you being treated for any ongoing conditions - diabetes, heart disease, anything requiring regular meds or specialists? Any hospitalizations or surgeries in the last two years? Any tobacco use?\"","compliance_locked":false,"sort_order":3,"verbatim":true,"lock_message":"Health profile complete"},
      {"key":"gate3Ok","section_number":4,"title":"Disclosure + Product Presentation","gate_field":"gate3Ok","body":"\"Before I show you options - these plans are not minimum essential coverage, not a substitute for ACA-compliant major medical, and pre-existing condition limitations may apply.\"\nDirection: Then present best-fit products based on health profile and budget.","compliance_locked":false,"sort_order":4,"verbatim":true,"lock_message":"Product presentation complete"},
      {"key":"gate4Ok","section_number":5,"title":"Comparison & Selection","gate_field":"gate4Ok","body":"\"So here's what makes sense for you - [recap products, premiums, key differences]. Which direction feels right?\"","compliance_locked":false,"sort_order":5,"verbatim":true,"lock_message":"Selection complete"},
      {"key":"gate5Ok","section_number":6,"title":"Ancillary","gate_field":"gate5Ok","body":"\"Now that we have your core plan, I'd recommend looking at [accident/critical illness/hospital indemnity/dental-vision] to fill in gaps. Usually just [price range] per month.\"","compliance_locked":false,"sort_order":6,"verbatim":true,"lock_message":"Ancillary discussion complete"},
      {"key":"gate6Ok","section_number":7,"title":"Enrollment","gate_field":"gate6Ok","body":"\"Let's get your application started. Your confirmation number is [number], effective date is [date], monthly premium is $[amount], first payment due by [date].\"","compliance_locked":false,"sort_order":7,"verbatim":true,"lock_message":"Enrollment complete"},
      {"key":"gate7Ok","section_number":8,"title":"Closing","gate_field":"gate7Ok","body":"\"To recap - you're [enrolled in / applied for] [Product Name] at $[amount]/month, coverage starts [date]. I'll check in with you in [timeframe] to make sure everything's set up. What's the best number and time to reach you? Anything else I can help with? Thank you for trusting New Gen Health Solutions.\"","compliance_locked":false,"sort_order":8,"verbatim":true,"lock_message":"Closing complete"}
    ]$json$::jsonb
  )
  ON CONFLICT (tenant_id, flow_type, version) DO UPDATE SET
    is_active = EXCLUDED.is_active,
    sections = EXCLUDED.sections,
    updated_at = now();
END $$;
